import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextValue {
  lang: Language;
  toggleLang: () => void;
  t: (key: string) => string;
}

const T: Record<string, Record<Language, string>> = {

  // ── Navbar ──────────────────────────────────────────────────────────────────
  'nav.overview':  { en: 'Overview',  hi: 'सारांश' },
  'nav.history':   { en: 'History',   hi: 'इतिहास' },
  'nav.info':      { en: 'Info',      hi: 'जानकारी' },
  'nav.profile':   { en: 'Profile',   hi: 'प्रोफ़ाइल' },
  'nav.signout':   { en: 'Sign out',  hi: 'साइन आउट' },

  // ── Common ──────────────────────────────────────────────────────────────────
  'common.fy':              { en: 'FY 2024–25',       hi: 'वित्त वर्ष 2024–25' },
  'common.calculated_on':   { en: 'Calculated on',    hi: 'गणना की गई' },
  'common.back':            { en: '← Back',           hi: '← वापस' },
  'common.continue':        { en: 'Continue →',       hi: 'जारी रखें →' },
  'common.skip':            { en: 'Skip (Optional) →',hi: 'छोड़ें (वैकल्पिक) →' },
  'common.edit':            { en: 'Edit',             hi: 'बदलें' },
  'common.add':             { en: 'Add',              hi: 'जोड़ें' },
  'common.cancel':          { en: 'Cancel',           hi: 'रद्द करें' },
  'common.retry':           { en: 'Retry',            hi: 'दोबारा कोशिश करें' },
  'common.recalculate':     { en: '↻ Recalculate',    hi: '↻ फिर से गणना करें' },
  'common.loading':         { en: 'Loading…',         hi: 'लोड हो रहा है…' },
  'common.gross_salary':    { en: 'Gross Salary',     hi: 'सकल वेतन' },
  'common.tds_paid':        { en: 'TDS Paid',         hi: 'TDS भुगतान' },
  'common.deductions':      { en: 'Deductions',       hi: 'कटौती' },
  'common.refund_due':      { en: 'Refund Due',    hi: 'वापसी देय' },
  'common.tax_payable':     { en: 'Tax Payable',   hi: 'देय कर' },
  'common.total_tax':       { en: 'Total Tax Liability', hi: 'कुल कर देयता' },
  'common.new_regime':      { en: 'New Tax Regime',   hi: 'नई कर व्यवस्था' },

  // ── Dashboard ───────────────────────────────────────────────────────────────
  'dash.title':      { en: 'File Your Income Tax Return',                              hi: 'अपना आयकर रिटर्न दाखिल करें' },
  'dash.subtitle':   { en: 'FY 2024–25 · New Tax Regime · Accurate calculations, zero complexity', hi: 'वित्त वर्ष 2024–25 · नई कर व्यवस्था · सटीक गणना, शून्य जटिलता' },
  'dash.not_sure':   { en: 'Not sure which form to file?',                             hi: 'कौन सा फॉर्म भरना है, पता नहीं?' },
  'dash.take_quiz':  { en: 'Take the eligibility quiz →',                              hi: 'पात्रता प्रश्नोत्तरी लें →' },

  // ── ITR cards ───────────────────────────────────────────────────────────────
  'itr1.title':       { en: 'ITR-1 (Sahaj)',          hi: 'ITR-1 (सहज)' },
  'itr1.tagline':     { en: 'For salaried individuals',hi: 'वेतनभोगी व्यक्तियों के लिए' },
  'itr1.desc':        { en: 'Salary income + one house property + interest income. Total income up to ₹50 lakh.', hi: 'वेतन आय + एक मकान + ब्याज आय। कुल आय ₹50 लाख तक।' },
  'itr1.who':         { en: 'Who should file ITR-1?',  hi: 'ITR-1 कौन भरे?' },
  'itr1.who1':        { en: '✓ Salaried employee (private or government)', hi: '✓ वेतनभोगी कर्मचारी (सरकारी या निजी)' },
  'itr1.who2':        { en: '✓ Has Form-16 from employer',                 hi: '✓ नियोक्ता से Form-16 है' },
  'itr1.who3':        { en: '✓ No stocks, mutual funds, or capital gains', hi: '✓ शेयर, म्यूचुअल फंड या पूंजीगत लाभ नहीं' },
  'itr1.who4':        { en: '✓ No business or professional income',        hi: '✓ कोई व्यावसायिक आय नहीं' },
  'itr1.cta':         { en: 'Start ITR-1 Filing',      hi: 'ITR-1 भरना शुरू करें' },
  'itr1.cta_resume':  { en: 'Resume ITR-1 Filing',     hi: 'ITR-1 जारी रखें' },
  'itr1.cta_view':    { en: 'View ITR-1 Result',       hi: 'ITR-1 परिणाम देखें' },

  'itr2.title':       { en: 'ITR-2',                  hi: 'ITR-2' },
  'itr2.tagline':     { en: 'For investors & traders', hi: 'निवेशकों और ट्रेडर्स के लिए' },
  'itr2.desc':        { en: 'Salary + capital gains from equity stocks, mutual funds, and house property income/loss.', hi: 'वेतन + इक्विटी, म्यूचुअल फंड से पूंजीगत लाभ और मकान संपत्ति आय/हानि।' },
  'itr2.who':         { en: 'Who should file ITR-2?',  hi: 'ITR-2 कौन भरे?' },
  'itr2.who1':        { en: '✓ Has equity stock or mutual fund gains/losses', hi: '✓ इक्विटी या म्यूचुअल फंड में लाभ/हानि है' },
  'itr2.who2':        { en: '✓ Has more than one house property',            hi: '✓ एक से अधिक मकान है' },
  'itr2.who3':        { en: '✓ Income from foreign assets or foreign salary', hi: '✓ विदेशी संपत्ति या विदेशी वेतन है' },
  'itr2.who4':        { en: '✓ Total income exceeds ₹50 lakh',               hi: '✓ कुल आय ₹50 लाख से अधिक है' },
  'itr2.cta':         { en: 'Start ITR-2 Filing',      hi: 'ITR-2 भरना शुरू करें' },
  'itr2.cta_resume':  { en: 'Resume ITR-2 Filing',     hi: 'ITR-2 जारी रखें' },
  'itr2.cta_view':    { en: 'View ITR-2 Result',       hi: 'ITR-2 परिणाम देखें' },

  // ── Quiz ────────────────────────────────────────────────────────────────────
  'quiz.title':              { en: 'Which ITR form should you file?',           hi: 'आपको कौन सा ITR फॉर्म भरना चाहिए?' },
  'quiz.subtitle':           { en: 'Answer 4 quick questions — takes 30 seconds', hi: '4 आसान सवालों के जवाब दें — 30 सेकंड लगते हैं' },
  'quiz.q1':                 { en: 'Do you have a salaried income (Form-16 from employer)?', hi: 'क्या आपकी वेतन आय है (नियोक्ता से Form-16)?' },
  'quiz.q2':                 { en: 'Did you trade in equity stocks or mutual funds this year?', hi: 'क्या आपने इस साल इक्विटी या म्यूचुअल फंड में निवेश किया?' },
  'quiz.q3':                 { en: 'Do you own more than one house property?',  hi: 'क्या आपके पास एक से अधिक मकान है?' },
  'quiz.q4':                 { en: 'Is your total income above ₹50 lakh?',     hi: 'क्या आपकी कुल आय ₹50 लाख से अधिक है?' },
  'quiz.yes':                { en: 'Yes',   hi: 'हाँ' },
  'quiz.no':                 { en: 'No',    hi: 'नहीं' },
  'quiz.result_itr1':        { en: 'You should file ITR-1', hi: 'आपको ITR-1 भरना चाहिए' },
  'quiz.result_itr2':        { en: 'You should file ITR-2', hi: 'आपको ITR-2 भरना चाहिए' },
  'quiz.result_itr1_reason': { en: 'Your income is from salary only. ITR-1 (Sahaj) is the right form for you.', hi: 'आपकी आय केवल वेतन से है। ITR-1 (सहज) आपके लिए सही फॉर्म है।' },
  'quiz.result_itr2_reason': { en: 'You have capital gains or complex income. ITR-2 covers all your income sources.', hi: 'आपके पास पूंजीगत लाभ या जटिल आय है। ITR-2 आपकी सभी आय स्रोतों को कवर करता है।' },
  'quiz.retake':             { en: '← Retake quiz', hi: '← दोबारा लें' },
  'quiz.close':              { en: 'Close',  hi: 'बंद करें' },

  // ── History ─────────────────────────────────────────────────────────────────
  'hist.title':          { en: 'Calculation History',          hi: 'गणना इतिहास' },
  'hist.subtitle':       { en: 'All your saved tax calculations', hi: 'आपकी सभी सहेजी गई कर गणनाएँ' },
  'hist.empty':          { en: 'No calculations saved yet',    hi: 'अभी तक कोई गणना सहेजी नहीं' },
  'hist.empty_sub':      { en: 'Complete a tax calculation and it will appear here automatically.', hi: 'कर गणना पूरी करें, यह स्वतः यहाँ दिखेगी।' },
  'hist.total_tax':      { en: 'Total Tax',      hi: 'कुल कर' },
  'hist.refund':         { en: 'Refund Due',     hi: 'वापसी देय' },
  'hist.payable':        { en: 'Tax Payable',    hi: 'देय कर' },
  'hist.salary':         { en: 'Salary Tax',     hi: 'वेतन कर' },
  'hist.stock':          { en: 'Stock Gains Tax',hi: 'शेयर लाभ कर' },
  'hist.mf':             { en: 'MF Equity Tax',  hi: 'म्यूचुअल फंड कर' },
  'hist.view':           { en: 'View Details',   hi: 'विवरण देखें' },
  'hist.delete':         { en: 'Delete',         hi: 'हटाएँ' },
  'hist.confirm_delete': { en: 'Delete this entry?', hi: 'यह प्रविष्टि हटाएँ?' },
  'hist.confirm_delete_sub': { en: 'This cannot be undone.', hi: 'यह पूर्ववत नहीं किया जा सकता।' },

  // ── ITR-1 Salary ─────────────────────────────────────────────────────────────
  's1.title':         { en: 'Salary Income',          hi: 'वेतन आय' },
  's1.subtitle':      { en: 'Upload your Form-16 to extract salary details', hi: 'वेतन विवरण के लिए Form-16 अपलोड करें' },
  's1.upload_label':  { en: 'Form-16 (PDF)',           hi: 'Form-16 (PDF)' },
  's1.upload_desc':   { en: 'Upload your Form-16 PDF for automatic data extraction', hi: 'स्वचालित डेटा निकालने के लिए Form-16 PDF अपलोड करें' },
  's1.parsing':       { en: 'Parsing document…',      hi: 'दस्तावेज़ पढ़ा जा रहा है…' },
  's1.success':       { en: '✓ Form-16 uploaded successfully', hi: '✓ Form-16 सफलतापूर्वक अपलोड हुआ' },
  's1.continue_review': { en: 'Continue to Review →', hi: 'समीक्षा पर जाएं →' },

  // ── ITR-1 Review ─────────────────────────────────────────────────────────────
  'r1.title':         { en: 'Review Data',             hi: 'डेटा की समीक्षा करें' },
  'r1.subtitle':      { en: 'Verify your information before calculating tax', hi: 'कर गणना से पहले जानकारी सत्यापित करें' },
  'r1.salary_section':{ en: 'Salary Income',           hi: 'वेतन आय' },
  'r1.confirm':       { en: 'Confirm & Calculate →',   hi: 'पुष्टि करें और गणना करें →' },
  'r1.edit_salary':   { en: '← Edit Salary',           hi: '← वेतन बदलें' },
  'r1.incomplete':    { en: 'Please complete the Salary section first', hi: 'पहले वेतन अनुभाग पूरा करें' },
  'r1.go_salary':     { en: 'Go to Salary →',          hi: 'वेतन पर जाएं →' },

  // ── ITR-1 Calculate ──────────────────────────────────────────────────────────
  'c1.title':         { en: 'Final Tax Summary (New Regime)', hi: 'अंतिम कर सारांश (नई व्यवस्था)' },
  'c1.last_calc':     { en: 'Last calculated:',         hi: 'अंतिम गणना:' },
  'c1.salary_tax':    { en: 'Salary Tax (before cess)', hi: 'वेतन कर (सेस से पहले)' },
  'c1.cess':          { en: 'Health & Education Cess (4%)', hi: 'स्वास्थ्य एवं शिक्षा उपकर (4%)' },
  'c1.total_liability':{ en: 'Total Tax Liability',     hi: 'कुल कर देयता' },
  'c1.refund':        { en: 'Refund Due:',              hi: 'वापसी देय:' },
  'c1.payable':       { en: 'Tax Payable:',             hi: 'देय कर:' },
  'c1.calculating':   { en: 'Calculating your tax…',   hi: 'आपकी कर गणना हो रही है…' },
  'c1.update':        { en: 'Update Calculation',       hi: 'गणना अपडेट करें' },
  'c1.recalculate':   { en: 'Recalculate',              hi: 'फिर से गणना करें' },
  'c1.back_review':   { en: '← Back to Review',        hi: '← समीक्षा पर वापस जाएं' },
  'c1.edit_salary':   { en: 'Edit Salary Details',      hi: 'वेतन विवरण बदलें' },
  'c1.no_result':     { en: 'No calculation result available', hi: 'कोई गणना परिणाम उपलब्ध नहीं' },
  'c1.calc_now':      { en: 'Calculate Now',            hi: 'अभी गणना करें' },
  'c1.complete_first':{ en: 'Please complete and review your data first', hi: 'पहले अपना डेटा पूरा करें और समीक्षा करें' },
  'c1.go_review':     { en: 'Go to Review →',           hi: 'समीक्षा पर जाएं →' },

  // ── ITR-2 Salary ─────────────────────────────────────────────────────────────
  's2.title':         { en: 'Salary Income',    hi: 'वेतन आय' },
  's2.subtitle':      { en: 'Upload your Form-16', hi: 'Form-16 अपलोड करें' },
  's2.upload_label':  { en: 'Form-16 (PDF)',    hi: 'Form-16 (PDF)' },
  's2.upload_desc':   { en: 'Upload your Form-16 PDF', hi: 'अपना Form-16 PDF अपलोड करें' },
  's2.parsing':       { en: 'Parsing…',         hi: 'पढ़ा जा रहा है…' },
  's2.success':       { en: '✓ Form-16 uploaded', hi: '✓ Form-16 अपलोड हुआ' },

  // ── ITR-2 Equity ─────────────────────────────────────────────────────────────
  'eq.title':         { en: 'Capital Gains',          hi: 'पूंजीगत लाभ' },
  'eq.subtitle':      { en: 'Upload your equity trades report from your broker', hi: 'अपने ब्रोकर से इक्विटी ट्रेड रिपोर्ट अपलोड करें' },
  'eq.broker_label':  { en: 'Select Broker',          hi: 'ब्रोकर चुनें' },
  'eq.broker_hint_groww':   { en: 'Groww parser will be used to process your equity trades report', hi: 'Groww पार्सर आपकी इक्विटी रिपोर्ट प्रोसेस करेगा' },
  'eq.broker_hint_zerodha': { en: 'Zerodha parser will be used to process your equity trades report', hi: 'Zerodha पार्सर आपकी इक्विटी रिपोर्ट प्रोसेस करेगा' },
  'eq.upload_label':  { en: 'Equity Trades Report (Excel)', hi: 'इक्विटी ट्रेड रिपोर्ट (Excel)' },
  'eq.parsing':       { en: 'Parsing report…',        hi: 'रिपोर्ट पढ़ी जा रही है…' },
  'eq.success':       { en: 'Equity report uploaded successfully', hi: 'इक्विटी रिपोर्ट सफलतापूर्वक अपलोड हुई' },

  // ── ITR-2 Mutual Funds ───────────────────────────────────────────────────────
  'mf.title':         { en: 'Mutual Funds',     hi: 'म्यूचुअल फंड' },
  'mf.subtitle':      { en: 'Upload your mutual fund capital gains report', hi: 'म्यूचुअल फंड पूंजीगत लाभ रिपोर्ट अपलोड करें' },
  'mf.upload_label':  { en: 'Mutual Fund Report (Excel)', hi: 'म्यूचुअल फंड रिपोर्ट (Excel)' },
  'mf.upload_desc':   { en: 'Upload your mutual fund capital gains report in Excel or CSV format', hi: 'Excel या CSV फॉर्मेट में म्यूचुअल फंड रिपोर्ट अपलोड करें' },
  'mf.parsing':       { en: 'Parsing mutual fund report…', hi: 'म्यूचुअल फंड रिपोर्ट पढ़ी जा रही है…' },
  'mf.success':       { en: 'Mutual fund report uploaded successfully', hi: 'म्यूचुअल फंड रिपोर्ट सफलतापूर्वक अपलोड हुई' },

  // ── ITR-2 House Property ─────────────────────────────────────────────────────
  'hp.title':         { en: 'House Property Income',  hi: 'मकान संपत्ति आय' },
  'hp.subtitle':      { en: 'Add all properties you own. Under the New Tax Regime, HP losses cannot be set off against salary — only carried forward 8 years (intra-head).', hi: 'अपनी सभी संपत्तियाँ जोड़ें। नई कर व्यवस्था में HP हानि को वेतन के विरुद्ध समायोजित नहीं किया जा सकता — केवल 8 वर्ष तक आगे ले जाया जा सकता है।' },
  'hp.add_another':   { en: '+ Add Another Property', hi: '+ एक और संपत्ति जोड़ें' },
  'hp.skip':          { en: 'Skip — no house property', hi: 'छोड़ें — कोई मकान संपत्ति नहीं' },
  'hp.calc_continue': { en: 'Calculate & Continue →', hi: 'गणना करें और जारी रखें →' },
  'hp.calculating':   { en: 'Calculating…',           hi: 'गणना हो रही है…' },
  'hp.net_income':    { en: 'Net HP Income (added to taxable income)', hi: 'शुद्ध HP आय (कर योग्य आय में जुड़ती है)' },
  'hp.total_loss':    { en: 'Total HP Loss (carry forward)', hi: 'कुल HP हानि (आगे ले जाएं)' },
  'hp.prop_type':     { en: 'Property Type',          hi: 'संपत्ति प्रकार' },
  'hp.remove':        { en: 'Remove',                 hi: 'हटाएँ' },
  'hp.preview':       { en: 'Preview This Property',  hi: 'इस संपत्ति का पूर्वावलोकन करें' },
  'hp.sop_label':     { en: 'Self-Occupied',          hi: 'स्वयं-अधिकृत' },
  'hp.sop_hint':      { en: 'You live in this property', hi: 'आप इस संपत्ति में रहते हैं' },
  'hp.lop_label':     { en: 'Let Out',                hi: 'किराए पर दी गई' },
  'hp.lop_hint':      { en: 'Rented out to a tenant', hi: 'किरायेदार को किराए पर दी गई' },
  'hp.dlop_label':    { en: 'Deemed Let Out',         hi: 'मानी गई किराए पर' },
  'hp.dlop_hint':     { en: '2+ houses — treated as rented', hi: '2+ मकान — किराए पर मानी जाती है' },
  'hp.sop_warning':   { en: 'New Tax Regime: Self-occupied property has NAV = ₹0. No home loan interest deduction (Sec 24b) is allowed.', hi: 'नई कर व्यवस्था: स्वयं-अधिकृत संपत्ति का NAV = ₹0। Sec 24b के तहत गृह ऋण ब्याज कटौती नहीं मिलती।' },
  'hp.gross_rent':    { en: 'Gross Rent Received (Annual)', hi: 'प्राप्त सकल किराया (वार्षिक)' },
  'hp.market_rent':   { en: 'Expected Market / Municipal Value', hi: 'अपेक्षित बाज़ार/नगर पालिका मूल्य' },
  'hp.gav_hint_lop':  { en: 'GAV = higher of actual rent or market rent', hi: 'GAV = वास्तविक किराया या बाज़ार किराया, जो अधिक हो' },
  'hp.gav_hint_dlop': { en: 'GAV for Deemed Let-Out = this value', hi: 'मानी गई संपत्ति का GAV = यह मूल्य' },
  'hp.municipal_tax': { en: 'Municipal Taxes Paid',   hi: 'नगर पालिका कर भुगतान' },
  'hp.municipal_hint':{ en: 'Only if paid by owner (not tenant)', hi: 'केवल यदि मालिक ने भुगतान किया हो (किरायेदार ने नहीं)' },
  'hp.loan_interest': { en: 'Home Loan Interest — Sec 24(b)', hi: 'गृह ऋण ब्याज — Sec 24(b)' },
  'hp.loan_hint':     { en: 'Fully deductible for Let-Out / Deemed Let-Out', hi: 'किराए पर दी गई संपत्ति के लिए पूर्णतः कटौती योग्य' },
  'hp.breakdown':     { en: 'Breakdown',              hi: 'विवरण' },
  'hp.gav':           { en: 'Gross Annual Value (GAV)', hi: 'सकल वार्षिक मूल्य (GAV)' },
  'hp.less_muni':     { en: 'Less: Municipal Taxes',  hi: 'घटाएं: नगर पालिका कर' },
  'hp.nav':           { en: 'Net Annual Value (NAV)',  hi: 'शुद्ध वार्षिक मूल्य (NAV)' },
  'hp.std_dedn':      { en: 'Less: 30% Standard Deduction (Sec 24a)', hi: 'घटाएं: 30% मानक कटौती (Sec 24a)' },
  'hp.interest_dedn': { en: 'Less: Home Loan Interest (Sec 24b)', hi: 'घटाएं: गृह ऋण ब्याज (Sec 24b)' },
  'hp.hp_income':     { en: 'HP Income',              hi: 'HP आय' },
  'hp.hp_loss':       { en: 'HP Loss',                hi: 'HP हानि' },
  'hp.no_setoff':     { en: '✗ Cannot set-off against Salary under New Regime', hi: '✗ नई व्यवस्था में वेतन के विरुद्ध समायोजन नहीं' },
  'hp.carry_fwd':     { en: '↷ Carry forward {n} years (intra-head only)', hi: '↷ {n} वर्ष आगे ले जाएं (केवल HP आय के विरुद्ध)' },

  // ── ITR-2 Review ─────────────────────────────────────────────────────────────
  'r2.title':         { en: 'Review Data',     hi: 'डेटा की समीक्षा' },
  'r2.subtitle':      { en: 'Verify all information before calculating tax', hi: 'कर गणना से पहले सभी जानकारी सत्यापित करें' },
  'r2.salary':        { en: 'Salary Income',   hi: 'वेतन आय' },
  'r2.equity':        { en: 'Equity Gains',    hi: 'इक्विटी लाभ' },
  'r2.mf':            { en: 'Mutual Fund Gains', hi: 'म्यूचुअल फंड लाभ' },
  'r2.hp':            { en: 'House Property',  hi: 'मकान संपत्ति' },
  'r2.no_hp':         { en: 'No house property added. Click "Add" to include property income/loss.', hi: 'कोई संपत्ति नहीं जोड़ी। संपत्ति आय/हानि जोड़ने के लिए "जोड़ें" पर क्लिक करें।' },
  'r2.stcg_before':   { en: 'STCG (before Jul 23)',   hi: 'STCG (23 जुलाई से पहले)' },
  'r2.stcg_after':    { en: 'STCG (after Jul 23)',    hi: 'STCG (23 जुलाई के बाद)' },
  'r2.ltcg_before':   { en: 'LTCG (before Jul 23)',   hi: 'LTCG (23 जुलाई से पहले)' },
  'r2.ltcg_after':    { en: 'LTCG (after Jul 23)',    hi: 'LTCG (23 जुलाई के बाद)' },
  'r2.eq_stcg':       { en: 'Equity STCG',   hi: 'इक्विटी STCG' },
  'r2.eq_ltcg':       { en: 'Equity LTCG',   hi: 'इक्विटी LTCG' },
  'r2.debt_stcg':     { en: 'Debt STCG',     hi: 'डेट STCG' },
  'r2.debt_ltcg':     { en: 'Debt LTCG',     hi: 'डेट LTCG' },
  'r2.net_hp_income': { en: 'Net HP income added to taxable income:', hi: 'कर योग्य आय में जुड़ी शुद्ध HP आय:' },
  'r2.total_hp_loss': { en: 'Total HP loss (carry forward):', hi: 'कुल HP हानि (आगे ले जाने योग्य):' },
  'r2.carry_fwd':     { en: 'Carry forward {n} years (cannot set off against salary)', hi: '{n} वर्ष आगे ले जाएं (वेतन के विरुद्ध समायोजन नहीं)' },
  'r2.self_occ':      { en: 'Self-Occupied', hi: 'स्वयं-अधिकृत' },
  'r2.let_out':       { en: 'Let Out',       hi: 'किराए पर दी गई' },
  'r2.deemed':        { en: 'Deemed Let Out',hi: 'मानी गई किराए पर' },
  'r2.edit_data':     { en: '← Edit Data',  hi: '← डेटा बदलें' },
  'r2.confirm':       { en: 'Confirm & Calculate →', hi: 'पुष्टि करें और गणना करें →' },
  'r2.incomplete':    { en: 'Please complete the Salary section first', hi: 'पहले वेतन अनुभाग पूरा करें' },
  'r2.go_salary':     { en: 'Go to Salary →', hi: 'वेतन पर जाएं →' },

  // ── ITR-2 Calculate ──────────────────────────────────────────────────────────
  'c2.title':               { en: 'Your Tax Summary',              hi: 'आपका कर सारांश' },
  'c2.subtitle':            { en: 'FY 2024–25 · New Tax Regime · ITR-2', hi: 'वित्त वर्ष 2024–25 · नई कर व्यवस्था · ITR-2' },
  'c2.total_tax':           { en: 'Total Tax Liability',           hi: 'कुल कर देयता' },
  'c2.incl_cess':           { en: 'incl. 4% cess',                hi: 'सहित 4% उपकर' },
  'c2.eff_rate':            { en: 'Effective Tax Rate',            hi: 'प्रभावी कर दर' },
  'c2.on_taxable':          { en: 'on taxable income',            hi: 'कर योग्य आय पर' },
  'c2.tds_paid':            { en: 'TDS Already Paid',             hi: 'पहले से भुगतान TDS' },
  'c2.tds_employer':        { en: 'deducted by employer (Form-16)', hi: 'नियोक्ता द्वारा काटा गया (Form-16)' },
  'c2.tds_vs_tax':          { en: 'TDS vs Tax Due',               hi: 'TDS बनाम देय कर' },
  'c2.tax_liability':       { en: 'Tax Liability',                hi: 'कर देयता' },
  'c2.refund_bank':         { en: 'Will be credited to your bank account', hi: 'आपके बैंक खाते में जमा होगा' },
  'c2.payable_challan':     { en: 'Pay via Challan 280 before filing', hi: 'दाखिल करने से पहले Challan 280 से भुगतान करें' },
  'c2.excess':              { en: 'Excess:',                      hi: 'अतिरिक्त:' },
  'c2.still_pay':           { en: 'Still to pay:',               hi: 'अभी भाकी:' },
  'c2.where_from':          { en: 'Where your tax comes from',   hi: 'आपका कर कहाँ से आता है' },
  'c2.salary_debt':         { en: 'Salary + Debt MF',            hi: 'वेतन + डेट MF' },
  'c2.slab_tax':            { en: 'slab tax',                    hi: 'स्लैब कर' },
  'c2.stock_gains':         { en: 'Equity Stock Gains',          hi: 'इक्विटी शेयर लाभ' },
  'c2.eq_mf':               { en: 'Equity Mutual Funds',         hi: 'इक्विटी म्यूचुअल फंड' },
  'c2.stcg_ltcg':           { en: 'STCG + LTCG',                hi: 'STCG + LTCG' },
  'c2.subtotal':            { en: 'Sub-total (before cess)',      hi: 'उप-योग (सेस से पहले)' },
  'c2.cess_line':           { en: '+ Health & Education Cess (4%)', hi: '+ स्वास्थ्य एवं शिक्षा उपकर (4%)' },
  'c2.salary_section':      { en: 'Salary income → taxable income → tax', hi: 'वेतन → कर योग्य आय → कर' },
  'c2.new_regime_note':     { en: 'Under the New Tax Regime, you get a flat ₹75,000 standard deduction. No 80C/HRA/NPS deductions are available.', hi: 'नई कर व्यवस्था में ₹75,000 की मानक कटौती मिलती है। 80C/HRA/NPS कटौती उपलब्ध नहीं है।' },
  'c2.gross_salary':        { en: 'Gross Salary (Form-16)',       hi: 'सकल वेतन (Form-16)' },
  'c2.std_dedn':            { en: 'Less: Standard Deduction (Sec 16)', hi: 'घटाएं: मानक कटौती (Sec 16)' },
  'c2.add_hp':              { en: 'Add: Net House Property Income', hi: 'जोड़ें: शुद्ध HP आय' },
  'c2.add_debt':            { en: 'Add: Debt MF Gains (treated as income)', hi: 'जोड़ें: डेट MF लाभ (आय माना गया)' },
  'c2.taxable_income':      { en: 'Taxable Income (Salary Head)', hi: 'कर योग्य आय (वेतन मद)' },
  'c2.slabs_title':         { en: 'New Regime Slabs',             hi: 'नई व्यवस्था के स्लैब' },
  'c2.rebate_87a':          { en: '✓ Section 87A Rebate applied — income ≤ ₹12,00,000, full tax waived', hi: '✓ धारा 87A छूट लागू — आय ≤ ₹12,00,000, पूरा कर माफ' },
  'c2.salary_tax_row':      { en: 'Tax on Salary + Debt MF (before cess)', hi: 'वेतन + डेट MF पर कर (सेस से पहले)' },
  'c2.equity_section':      { en: 'Equity stocks — capital gains tax', hi: 'इक्विटी शेयर — पूंजीगत लाभ कर' },
  'c2.equity_note':         { en: 'Tax rates changed on July 23, 2024 (Budget 2024). STCG: 15% → 20%; LTCG: 10% → 12.5%. Your gains are split by date.', hi: '23 जुलाई 2024 को कर दरें बदलीं (बजट 2024)। STCG: 15% → 20%; LTCG: 10% → 12.5%। आपका लाभ तारीख के अनुसार बंटा है।' },
  'c2.stcg_before':         { en: 'STCG — before Jul 23, 2024',   hi: 'STCG — 23 जुलाई 2024 से पहले' },
  'c2.stcg_after':          { en: 'STCG — after Jul 23, 2024',    hi: 'STCG — 23 जुलाई 2024 के बाद' },
  'c2.ltcg_before':         { en: 'LTCG — before Jul 23, 2024',   hi: 'LTCG — 23 जुलाई 2024 से पहले' },
  'c2.ltcg_after':          { en: 'LTCG — after Jul 23, 2024',    hi: 'LTCG — 23 जुलाई 2024 के बाद' },
  'c2.stcg_tax':            { en: 'STCG Tax',    hi: 'STCG कर' },
  'c2.ltcg_tax':            { en: 'LTCG Tax',    hi: 'LTCG कर' },
  'c2.total_stock_tax':     { en: 'Total Equity Stock Tax', hi: 'कुल इक्विटी शेयर कर' },
  'c2.mf_section':          { en: 'Mutual funds — capital gains tax', hi: 'म्यूचुअल फंड — पूंजीगत लाभ कर' },
  'c2.mf_note':             { en: 'Equity MFs are taxed separately (STCG 20%, LTCG 12.5% after ₹1.25L exemption). Debt MFs (post Apr 2023) are added to income and taxed at your slab rate.', hi: 'इक्विटी MF पर अलग से कर (STCG 20%, LTCG 12.5% ₹1.25 लाख छूट के बाद)। डेट MF (अप्रैल 2023 के बाद) आय में जोड़े जाते हैं।' },
  'c2.eq_mf_stcg':          { en: 'Equity MF — STCG',    hi: 'इक्विटी MF — STCG' },
  'c2.eq_mf_ltcg':          { en: 'Equity MF — LTCG',    hi: 'इक्विटी MF — LTCG' },
  'c2.ltcg_exemption':      { en: 'Less: LTCG Exemption (Sec 112A)', hi: 'घटाएं: LTCG छूट (Sec 112A)' },
  'c2.taxable_eq_ltcg':     { en: 'Taxable Equity MF LTCG', hi: 'कर योग्य इक्विटी MF LTCG' },
  'c2.eq_mf_tax':           { en: 'Equity MF Tax',        hi: 'इक्विटी MF कर' },
  'c2.debt_stcg':           { en: 'Debt MF — STCG',       hi: 'डेट MF — STCG' },
  'c2.debt_ltcg':           { en: 'Debt MF — LTCG',       hi: 'डेट MF — LTCG' },
  'c2.debt_added':          { en: 'Total added to Salary income', hi: 'कुल वेतन आय में जोड़ा गया' },
  'c2.hp_section':          { en: 'House property income / loss', hi: 'मकान संपत्ति आय / हानि' },
  'c2.hp_note':             { en: 'Under the New Regime, only positive HP income is added to your taxable income. HP losses cannot be set off against salary — only carried forward 8 years against future HP income.', hi: 'नई व्यवस्था में केवल सकारात्मक HP आय कर योग्य आय में जुड़ती है। HP हानि वेतन के विरुद्ध नहीं — केवल 8 वर्ष तक HP आय के विरुद्ध आगे ले जाई जा सकती है।' },
  'c2.hp_net_added':        { en: 'Net HP Income added to taxable income', hi: 'कर योग्य आय में जुड़ी शुद्ध HP आय' },
  'c2.hp_loss_carry':       { en: 'Total HP Loss (carry forward only)', hi: 'कुल HP हानि (केवल आगे ले जाने योग्य)' },
  'c2.final_section':       { en: 'Final tax reconciliation', hi: 'अंतिम कर मिलान' },
  'c2.salary_row':          { en: 'Tax on Salary + Debt MF', hi: 'वेतन + डेट MF पर कर' },
  'c2.stock_row':           { en: 'Tax on Equity Stock Gains', hi: 'इक्विटी शेयर लाभ पर कर' },
  'c2.mf_row':              { en: 'Tax on Equity Mutual Funds', hi: 'इक्विटी म्यूचुअल फंड पर कर' },
  'c2.cess_row':            { en: 'Health & Education Cess (4%)', hi: 'स्वास्थ्य एवं शिक्षा उपकर (4%)' },
  'c2.less_tds':            { en: 'Less: TDS Already Deducted (Form-16)', hi: 'घटाएं: पहले से काटा TDS (Form-16)' },
  'c2.refund_label':        { en: 'Refund Due to You',   hi: 'आपको वापसी देय' },
  'c2.payable_label':       { en: 'Balance Tax Payable',  hi: 'शेष देय कर' },
  'c2.challan_tip':         { en: 'Pay via Challan 280 on the Income Tax e-filing portal before submitting your ITR to avoid interest charges under Sec 234B / 234C.', hi: 'Sec 234B/234C के तहत ब्याज से बचने के लिए ITR जमा करने से पहले Income Tax e-filing पोर्टल पर Challan 280 से भुगतान करें।' },
  'c2.refund_tip':          { en: 'Your refund will be credited to your pre-validated bank account after ITR processing — typically within 30–45 days of filing.', hi: 'आपका रिफंड ITR प्रोसेसिंग के बाद आपके पूर्व-सत्यापित बैंक खाते में जमा होगा — आमतौर पर दाखिल करने के 30–45 दिनों में।' },
  'c2.back_review':         { en: '← Back to Review',  hi: '← समीक्षा पर वापस' },
  'c2.edit_salary':         { en: 'Edit Salary',        hi: 'वेतन बदलें' },
  'c2.edit_equity':         { en: 'Edit Equity',        hi: 'इक्विटी बदलें' },
  'c2.edit_mf':             { en: 'Edit MF',            hi: 'MF बदलें' },
  'c2.edit_hp':             { en: 'Edit HP',            hi: 'HP बदलें' },
  'c2.complete_first':      { en: 'Please complete and review your data first', hi: 'पहले अपना डेटा पूरा करें और समीक्षा करें' },
  'c2.go_review':           { en: 'Go to Review →',    hi: 'समीक्षा पर जाएं →' },
  'c2.calculating':         { en: 'Calculating your tax liability…', hi: 'आपकी कर देयता की गणना हो रही है…' },
  'c2.applying_rules':      { en: 'Applying FY 2024-25 New Tax Regime rules', hi: 'वित्त वर्ष 2024-25 नई कर व्यवस्था के नियम लागू हो रहे हैं' },
  'c2.no_result':           { en: 'No calculation result yet', hi: 'अभी कोई परिणाम नहीं' },
  'c2.calc_now':            { en: 'Calculate Now',      hi: 'अभी गणना करें' },
  'c2.retry':               { en: 'Retry Calculation',  hi: 'दोबारा गणना करें' },
  'c2.self_occ':            { en: 'Self-Occupied',      hi: 'स्वयं-अधिकृत' },
  'c2.let_out':             { en: 'Let Out',            hi: 'किराए पर दी गई' },
  'c2.deemed_let_out':      { en: 'Deemed Let Out',     hi: 'मानी गई किराए पर' },
  'c2.loss_carry':          { en: 'Loss of {amt} cannot be set off against salary · Carry forward {n} years', hi: '{amt} की हानि वेतन के विरुद्ध समायोजित नहीं — {n} वर्ष आगे ले जाएं' },
  'c2.gav':                 { en: 'GAV:',               hi: 'GAV:' },
  'c2.muni_tax':            { en: 'Municipal taxes:',   hi: 'नगर पालिका कर:' },
  'c2.nav':                 { en: 'NAV:',               hi: 'NAV:' },
  'c2.std_dedn30':          { en: 'Std deduction (30%):',hi: 'मानक कटौती (30%):' },
  'c2.loan_int':            { en: 'Home loan interest Sec 24(b):', hi: 'गृह ऋण ब्याज Sec 24(b):' },

  // ── Info page ────────────────────────────────────────────────────────────────
  'info.title':             { en: 'How tax is calculated',  hi: 'कर की गणना कैसे होती है' },
  'info.subtitle':          { en: 'A clear explanation of how SmartTax computes your tax under the New Tax Regime (FY 2024–25).', hi: 'SmartTax नई कर व्यवस्था (वित्त वर्ष 2024–25) के तहत कर की गणना कैसे करता है, इसकी स्पष्ट व्याख्या।' },
  'info.salary_title':      { en: 'Salary income',          hi: 'वेतन आय' },
  'info.std_dedn_title':    { en: 'Standard deduction',     hi: 'मानक कटौती' },
  'info.std_dedn_desc':     { en: 'A flat deduction of ₹75,000 is applied to your gross salary.', hi: 'आपके सकल वेतन से ₹75,000 की मानक कटौती लागू होती है।' },
  'info.slabs_title':       { en: 'Tax slabs',              hi: 'कर स्लैब' },
  'info.slabs_desc':        { en: 'The remaining income is taxed using the new regime slabs:', hi: 'शेष आय पर नई व्यवस्था के स्लैब के अनुसार कर लगता है:' },
  'info.rebate_title':      { en: 'Section 87A rebate',     hi: 'धारा 87A छूट' },
  'info.rebate_desc':       { en: 'If your taxable income is ₹12,00,000 or less, your tax becomes zero (including cess).', hi: 'यदि आपकी कर योग्य आय ₹12,00,000 या कम है, तो आपका कर शून्य हो जाता है (सेस सहित)।' },
  'info.cess_title':        { en: 'Health & education cess', hi: 'स्वास्थ्य एवं शिक्षा उपकर' },
  'info.cess_desc':         { en: 'A 4% cess is applied on the final tax amount.', hi: 'अंतिम कर राशि पर 4% उपकर लगता है।' },
  'info.equity_title':      { en: 'Equity stocks',          hi: 'इक्विटी शेयर' },
  'info.stcg_title':        { en: 'Short term capital gains (STCG)', hi: 'अल्पकालिक पूंजीगत लाभ (STCG)' },
  'info.stcg_desc':         { en: 'Shares sold within 1 year', hi: '1 वर्ष के अंदर बेचे गए शेयर' },
  'info.stcg_15':           { en: '15% for sales before 23 July 2024', hi: '23 जुलाई 2024 से पहले की बिक्री पर 15%' },
  'info.stcg_20':           { en: '20% for sales on or after 23 July 2024', hi: '23 जुलाई 2024 को या उसके बाद की बिक्री पर 20%' },
  'info.ltcg_title':        { en: 'Long term capital gains (LTCG)', hi: 'दीर्घकालिक पूंजीगत लाभ (LTCG)' },
  'info.ltcg_desc':         { en: 'Shares held for more than 1 year', hi: '1 वर्ष से अधिक रखे गए शेयर' },
  'info.ltcg_exempt':       { en: 'First ₹1,25,000 is tax-free', hi: 'पहला ₹1,25,000 कर-मुक्त' },
  'info.ltcg_above':        { en: 'Amount above exemption:',hi: 'छूट से ऊपर की राशि:' },
  'info.ltcg_10':           { en: '10% before 23 July 2024',  hi: '23 जुलाई 2024 से पहले 10%' },
  'info.ltcg_125':          { en: '12.5% after 23 July 2024', hi: '23 जुलाई 2024 के बाद 12.5%' },
  'info.eq_mf_title':       { en: 'Equity mutual funds',    hi: 'इक्विटी म्यूचुअल फंड' },
  'info.eq_mf_st_title':    { en: 'Short term (less than 1 year)', hi: 'अल्पकालिक (1 वर्ष से कम)' },
  'info.eq_mf_st_desc':     { en: 'Taxed at 20%',           hi: '20% पर कर' },
  'info.eq_mf_lt_title':    { en: 'Long term (more than 1 year)', hi: 'दीर्घकालिक (1 वर्ष से अधिक)' },
  'info.eq_mf_lt_exempt':   { en: 'First ₹1,25,000 is exempt', hi: 'पहला ₹1,25,000 छूट में' },
  'info.eq_mf_lt_rate':     { en: 'Remaining amount taxed at 12.5%', hi: 'शेष राशि पर 12.5% कर' },
  'info.debt_mf_title':     { en: 'Debt mutual funds',      hi: 'डेट म्यूचुअल फंड' },
  'info.debt_mf_desc':      { en: 'Post April 2023, all debt mutual fund gains are treated as normal income, regardless of holding period.', hi: 'अप्रैल 2023 के बाद, सभी डेट म्यूचुअल फंड लाभ को होल्डिंग अवधि की परवाह किए बिना सामान्य आय माना जाता है।' },
  'info.debt_no_ltcg':      { en: '• No LTCG benefit',      hi: '• कोई LTCG लाभ नहीं' },
  'info.debt_no_idx':       { en: '• No indexation',        hi: '• कोई इंडेक्सेशन नहीं' },
  'info.debt_no_exempt':    { en: '• No exemption',         hi: '• कोई छूट नहीं' },
  'info.debt_added':        { en: '• Added directly to salary income', hi: '• सीधे वेतन आय में जोड़ा जाता है' },
  'info.debt_slab':         { en: '• Taxed as per your slab rate', hi: '• आपकी स्लैब दर के अनुसार कर' },
  'info.debt_example':      { en: 'Example',                hi: 'उदाहरण' },
  'info.debt_ex_salary':    { en: 'Salary',                 hi: 'वेतन' },
  'info.debt_ex_gain':      { en: 'Debt MF gain',           hi: 'डेट MF लाभ' },
  'info.debt_ex_total':     { en: 'Total income',           hi: 'कुल आय' },
  'info.final_title':       { en: 'Final tax summary',      hi: 'अंतिम कर सारांश' },
  'info.final_desc':        { en: 'Your final tax is the sum of:', hi: 'आपका अंतिम कर इनका योग है:' },
  'info.final_1':           { en: '• Salary tax (including debt MF income)', hi: '• वेतन कर (डेट MF आय सहित)' },
  'info.final_2':           { en: '• Equity stock capital gains tax', hi: '• इक्विटी शेयर पूंजीगत लाभ कर' },
  'info.final_3':           { en: '• Equity mutual fund tax', hi: '• इक्विटी म्यूचुअल फंड कर' },
  'info.tds_sub':           { en: 'From this total, any TDS already deducted is subtracted.', hi: 'इस कुल से, पहले से काटा गया TDS घटाया जाता है।' },
  'info.if_tds_gt':         { en: 'If TDS > total tax',    hi: 'यदि TDS > कुल कर' },
  'info.refund_due':        { en: 'Refund due',             hi: 'वापसी देय' },
  'info.if_tds_lt':         { en: 'If TDS < total tax',    hi: 'यदि TDS < कुल कर' },
  'info.tax_payable':       { en: 'Tax payable',            hi: 'देय कर' },
  'info.disclaimer':        { en: 'SmartTax follows the latest available income tax rules. This explanation is for clarity and education. Final liability may vary based on personal circumstances.', hi: 'SmartTax नवीनतम आयकर नियमों का पालन करता है। यह स्पष्टता और शिक्षा के लिए है। अंतिम देयता व्यक्तिगत परिस्थितियों के आधार पर भिन्न हो सकती है।' },
  'info.nil':               { en: 'Nil',  hi: 'शून्य' },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() =>
    (localStorage.getItem('smarttax_lang') as Language) ?? 'en'
  );

  useEffect(() => {
    localStorage.setItem('smarttax_lang', lang);
  }, [lang]);

  const toggleLang = () => setLang(prev => (prev === 'en' ? 'hi' : 'en'));

  const t = (key: string): string => T[key]?.[lang] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = (): LanguageContextValue => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider');
  return ctx;
};
