import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'bn' | 'or' | 'ta' | 'te';

interface LanguageContextValue {
  lang: Language;
  toggleLang: () => void;
  t: (key: string) => string;
}

const T: Record<string, Record<Language, string>> = {

  // ── Navbar ──────────────────────────────────────────────────────────────────
  'nav.overview':  { en: 'Overview',  hi: 'सारांश', bn: 'সারসংক্ষেপ', or: 'ସାରାଂଶ', ta: 'மேலோட்டம்', te: 'అవలోకనం' },
  'nav.history':   { en: 'History',   hi: 'इतिहास', bn: 'ইতিহাস', or: 'ଇତିହାସ', ta: 'வரலாறு', te: 'చరిత్ర' },
  'nav.info':      { en: 'Info',      hi: 'जानकारी', bn: 'তথ্য', or: 'ସୂଚନା', ta: 'தகவல்', te: 'సమాచారం' },
  'nav.profile':   { en: 'Profile',   hi: 'प्रोफ़ाइल', bn: 'প্রোফাইল', or: 'ପ୍ରୋଫାଇଲ', ta: 'சுயவிவரம்', te: 'ప్రొఫైల్' },
  'nav.signout':   { en: 'Sign out',  hi: 'साइन आउट', bn: 'সাইন আউট', or: 'ସାଇନ ଆଉଟ', ta: 'வெளியேறு', te: 'సైన్ అవుట్' },

  // ── Common ──────────────────────────────────────────────────────────────────
  'common.fy':              { en: 'FY 2024–25',       hi: 'वित्त वर्ष 2024–25' , bn: 'FY 2024–25', or: 'FY 2024–25', ta: 'FY 2024–25', te: 'FY 2024–25' },
  'common.calculated_on':   { en: 'Calculated on',    hi: 'गणना की गई' , bn: 'গণনা করা হয়েছে', or: 'ਗ ক', ta: 'கணக்கிடப்பட்டது', te: 'లెక్కించబడింది' },
  'common.back':            { en: '← Back',           hi: '← वापस' , bn: '← ফিরুন', or: '← ফিরুন', ta: '← பின்செல்', te: '← వెనక్కి' },
  'common.continue':        { en: 'Continue →',       hi: 'जारी रखें →' , bn: 'চালিয়ে যান →', or: 'চালিয়ে যান →', ta: 'தொடரவும் →', te: 'కొనసాగండి →' },
  'common.skip':            { en: 'Skip (Optional) →',hi: 'छोड़ें (वैकल्पिक) →' , bn: 'এড়িয়ে যান (ঐচ্ছিক) →', or: 'এড়িয়ে যান →', ta: 'தவிர்க்கவும் (விருப்பம்) →', te: 'వదలండి (ఐచ్ఛికం) →' },
  'common.edit':            { en: 'Edit',             hi: 'बदलें' , bn: 'সম্পাদনা', or: 'ਸ', ta: 'திருத்து', te: 'మార్చు' },
  'common.add':             { en: 'Add',              hi: 'जोड़ें' , bn: 'যোগ করুন', or: 'যোগ', ta: 'சேர்', te: 'జోడించు' },
  'common.cancel':          { en: 'Cancel',           hi: 'रद्द करें' , bn: 'বাতিল', or: 'বাতিল', ta: 'ரத்துசெய்', te: 'రద్దు చేయి' },
  'common.retry':           { en: 'Retry',            hi: 'दोबारा कोशिश करें' , bn: 'আবার চেষ্টা করুন', or: 'আবার চেষ্টা', ta: 'மீண்டும் முயல்', te: 'మళ్ళీ ప్రయత్నించు' },
  'common.recalculate':     { en: '↻ Recalculate',    hi: '↻ फिर से गणना करें' , bn: '↻ পুনরায় গণনা', or: '↻ পুনরায় গণনা', ta: '↻ மீண்டும் கணக்கிடு', te: '↻ మళ్ళీ లెక్కించు' },
  'common.loading':         { en: 'Loading…',         hi: 'लोड हो रहा है…' , bn: 'লোড হচ্ছে…', or: 'লোড হচ্ছে…', ta: 'ஏற்றப்படுகிறது…', te: 'లోడ్ అవుతోంది…' },
  'common.gross_salary':    { en: 'Gross Salary',     hi: 'सकल वेतन' , bn: 'মোট বেতন', or: 'মোট বেতন', ta: 'மொத்த சம்பளம்', te: 'స్థూల జీతం' },
  'common.tds_paid':        { en: 'TDS Paid',         hi: 'TDS भुगतान' , bn: 'TDS প্রদান', or: 'TDS প্রদান', ta: 'TDS செலுத்தப்பட்டது', te: 'TDS చెల్లించారు' },
  'common.deductions':      { en: 'Deductions',       hi: 'कटौती' , bn: 'কাটছাঁট', or: 'কাটছাঁট', ta: 'விலக்குகள்', te: 'తగ్గింపులు' },
  'common.refund_due':      { en: 'Refund Due',    hi: 'वापसी देय' , bn: 'ফেরত প্রাপ্য', or: 'ফেরত প্রাপ্য', ta: 'திரும்பப் பெற வேண்டியது', te: 'రিఫండ్ రావాల్సినది' },
  'common.tax_payable':     { en: 'Tax Payable',   hi: 'देय कर' , bn: 'প্রদেয় কর', or: 'ପ୍ରଦେୟ ଆୟକର', ta: 'செலுத்த வேண்டிய வரி', te: 'చెల్లించవలసిన పన్ను' },
  'common.total_tax':       { en: 'Total Tax Liability', hi: 'कुल कर देयता' , bn: 'মোট কর দায়', or: 'মোট ক দ', ta: 'மொத்த வரி பொறுப்பு', te: 'మొత్తం పన్ను బాధ్యత' },
  'common.new_regime':      { en: 'New Tax Regime', hi: 'नई कर व्यवस्था', bn: 'নতুন কর ব্যবস্থা', or: 'ନୂଆ କର ବ୍ୟବସ୍ଥା', ta: 'புதிய வரி முறை', te: 'కొత్త పన్ను విధానం' },

  // ── Dashboard ───────────────────────────────────────────────────────────────
  'dash.title':      { en: 'File Your Income Tax Return', hi: 'अपना आयकर रिटर्न दाखिल करें', bn: 'আপনার আয়কর রিটার্ন দাখিল করুন', or: 'ଆପଣଙ୍କ ଆୟକର ରିଟର୍ଣ ଦାଖଲ କରନ୍ତୁ', ta: 'உங்கள் வருமான வரி தாக்கல் செய்யுங்கள்', te: 'మీ ఆదాయపు పన్ను రిటర్న్ దాఖలు చేయండి' },
  'dash.subtitle':   { en: 'FY 2024–25 · New Tax Regime · Accurate calculations, zero complexity', hi: 'वित्त वर्ष 2024–25 · नई कर व्यवस्था · सटीक गणना, शून्य जटिलता' , bn: 'FY 2024–25 · New Tax Regime · Accurate calculations, zero complexity', or: 'FY 2024–25 · New Tax Regime · Accurate calculations, zero complexity', ta: 'FY 2024–25 · New Tax Regime · Accurate calculations, zero complexity', te: 'FY 2024–25 · New Tax Regime · Accurate calculations, zero complexity' },
  'dash.not_sure':   { en: 'Not sure which form to file?', hi: 'कौन सा फॉर्म भरना है, पता नहीं?', bn: 'কোন ফর্ম জমা দিতে হবে জানেন না?', or: 'କେଉଁ ଫର୍ମ ଦାଖଲ କରିବେ ଜାଣନ୍ତି ନାହିଁ?', ta: 'எந்த படிவம் தாக்கல் செய்வது என்று தெரியவில்லையா?', te: 'ఏ ఫారం దాఖలు చేయాలో తెలియదా?' },
  'dash.take_quiz':  { en: 'Take the eligibility quiz →', hi: 'पात्रता प्रश्नोत्तरी लें →', bn: 'যোগ্যতা কুইজ নিন →', or: 'ଯୋଗ୍ୟତା କ୍ୱିଜ ନିଅନ୍ତୁ →', ta: 'தகுதி வினாடி வினா எடுங்கள் →', te: 'అర్హత క్విజ్ తీసుకోండి →' },

  // ── ITR cards ───────────────────────────────────────────────────────────────
  'itr1.title':       { en: 'ITR-1 (Sahaj)',          hi: 'ITR-1 (सहज)' , bn: 'ITR-1 (সহজ)', or: 'ITR-1 (সহজ)', ta: 'ITR-1 (சகஜ்)', te: 'ITR-1 (సహజ్)' },
  'itr1.tagline':     { en: 'For salaried individuals',hi: 'वेतनभोगी व्यक्तियों के लिए' , bn: 'বেতনভোগীদের জন্য', or: 'ব ব জ', ta: 'சம்பளதாரர்களுக்கு', te: 'జీతదారులకు' },
  'itr1.desc':        { en: 'Salary income + one house property + interest income. Total income up to ₹50 lakh.', hi: 'वेतन आय + एक मकान + ब्याज आय। कुल आय ₹50 लाख तक।' , bn: 'Salary income + one house property + interest income. Total income up to ₹50 lakh.', or: 'Salary income + one house property + interest income. Total income up to ₹50 lakh.', ta: 'Salary income + one house property + interest income. Total income up to ₹50 lakh.', te: 'Salary income + one house property + interest income. Total income up to ₹50 lakh.' },
  'itr1.who':         { en: 'Who should file ITR-1?',  hi: 'ITR-1 कौन भरे?' , bn: 'ITR-1 কে দাখিল করবেন?', or: 'ITR-1 ক দ', ta: 'ITR-1 யார் தாக்கல் செய்ய வேண்டும்?', te: 'ITR-1 ఎవరు దాఖలు చేయాలి?' },
  'itr1.who1':        { en: '✓ Salaried employee (private or government)', hi: '✓ वेतनभोगी कर्मचारी (सरकारी या निजी)' , bn: '✓ বেতনভোগী কর্মী (সরকারি বা বেসরকারি)', or: '✓ ব ক', ta: '✓ சம்பளதாரர் (தனியார் அல்லது அரசு)', te: '✓ జీతదారు (ప్రైవేట్ లేదా ప్రభుత్వం)' },
  'itr1.who2':        { en: '✓ Has Form-16 from employer',                 hi: '✓ नियोक्ता से Form-16 है' , bn: '✓ নিয়োগকর্তার Form-16 আছে', or: '✓ ন Form-16', ta: '✓ முதலாளியிடமிருந்து Form-16 உள்ளது', te: '✓ యజమాని నుండి Form-16 ఉంది' },
  'itr1.who3':        { en: '✓ No stocks, mutual funds, or capital gains', hi: '✓ शेयर, म्यूचुअल फंड या पूंजीगत लाभ नहीं' , bn: '✓ শেয়ার, MF বা মূলধনী লাভ নেই', or: '✓ শেয়ার নেই', ta: '✓ பங்குகள், MF அல்லது மூலதன ஆதாயம் இல்லை', te: '✓ స్టాక్స్, MF లేదా మూలధన లాభాలు లేవు' },
  'itr1.who4':        { en: '✓ No business or professional income',        hi: '✓ कोई व्यावसायिक आय नहीं' , bn: '✓ ব্যবসায়িক বা পেশাদার আয় নেই', or: '✓ ব আয় নেই', ta: '✓ வியாபார அல்லது தொழில்முறை வருமானம் இல்லை', te: '✓ వ్యాపార లేదా వృత్తిపరమైన ఆదాయం లేదు' },
  'itr1.cta':         { en: 'Start ITR-1 Filing',      hi: 'ITR-1 भरना शुरू करें' , bn: 'ITR-1 দাখিল শুরু করুন', or: 'ITR-1 দাখিল শুরু', ta: 'ITR-1 தாக்கல் தொடங்குங்கள்', te: 'ITR-1 దాఖలు ప్రారంభించండి' },
  'itr1.cta_resume':  { en: 'Resume ITR-1 Filing',     hi: 'ITR-1 जारी रखें' , bn: 'ITR-1 দাখিল পুনরায় শুরু করুন', or: 'ITR-1 দাখিল', ta: 'ITR-1 தாக்கலை தொடரவும்', te: 'ITR-1 దాఖలు పున:ప్రారంభించండి' },
  'itr1.cta_view':    { en: 'View ITR-1 Result',       hi: 'ITR-1 परिणाम देखें' , bn: 'ITR-1 ফলাফল দেখুন', or: 'ITR-1 ফলাফল', ta: 'ITR-1 முடிவை பாருங்கள்', te: 'ITR-1 ఫలితం చూడండి' },

  'itr2.title':       { en: 'ITR-2',                  hi: 'ITR-2' , bn: 'ITR-2', or: 'ITR-2', ta: 'ITR-2', te: 'ITR-2' },
  'itr2.tagline':     { en: 'For investors & traders', hi: 'निवेशकों और ट्रेडर्स के लिए' , bn: 'বিনিয়োগকারীদের জন্য', or: 'ব ব জ', ta: 'முதலீட்டாளர்களுக்கு', te: 'పెట్టుబడిదారులకు' },
  'itr2.desc':        { en: 'Salary + capital gains from equity stocks, mutual funds, and house property income/loss.', hi: 'वेतन + इक्विटी, म्यूचुअल फंड से पूंजीगत लाभ और मकान संपत्ति आय/हानि।' , bn: 'Salary + capital gains from equity stocks, mutual funds, and house property income/loss.', or: 'Salary + capital gains from equity stocks, mutual funds, and house property income/loss.', ta: 'Salary + capital gains from equity stocks, mutual funds, and house property income/loss.', te: 'Salary + capital gains from equity stocks, mutual funds, and house property income/loss.' },
  'itr2.who':         { en: 'Who should file ITR-2?',  hi: 'ITR-2 कौन भरे?' , bn: 'ITR-2 কে দাখিল করবেন?', or: 'ITR-2 ক দ', ta: 'ITR-2 யார் தாக்கல் செய்ய வேண்டும்?', te: 'ITR-2 ఎవరు దాఖలు చేయాలి?' },
  'itr2.who1':        { en: '✓ Has equity stock or mutual fund gains/losses', hi: '✓ इक्विटी या म्यूचुअल फंड में लाभ/हानि है' , bn: '✓ ইক্যুইটি বা MF লাভ/ক্ষতি আছে', or: '✓ ই MF ল', ta: '✓ ஈக்விட்டி அல்லது MF ஆதாயம்/இழப்பு உள்ளது', te: '✓ ఈక్విటీ లేదా MF లాభాలు/నష్టాలు ఉన్నాయి' },
  'itr2.who2':        { en: '✓ Has more than one house property',            hi: '✓ एक से अधिक मकान है' , bn: '✓ একের বেশি বাড়ি আছে', or: '✓ এক এর বেশি বাড়ি', ta: '✓ ஒன்றுக்கும் மேற்பட்ட வீடு உள்ளது', te: '✓ ఒకటి కంటే ఎక్కువ ఇళ్ళు ఉన్నాయి' },
  'itr2.who3':        { en: '✓ Income from foreign assets or foreign salary', hi: '✓ विदेशी संपत्ति या विदेशी वेतन है' , bn: '✓ বিদেশী সম্পদ বা বিদেশী বেতন থেকে আয়', or: '✓ বিদেশী আয়', ta: '✓ வெளிநாட்டு சொத்துகள் அல்லது சம்பளத்திலிருந்து வருமானம்', te: '✓ విదేశీ ఆస్తులు లేదా విదేశీ జీతం నుండి ఆదాయం' },
  'itr2.who4':        { en: '✓ Total income exceeds ₹50 lakh',               hi: '✓ कुल आय ₹50 लाख से अधिक है' , bn: '✓ মোট আয় ₹50 লক্ষ ছাড়িয়েছে', or: '✓ মোট ₹50 লাখ', ta: '✓ மொத்த வருமானம் ₹50 லட்சத்திற்கு மேல்', te: '✓ మొత్తం ఆదాయం ₹50 లక్షలు దాటింది' },
  'itr2.cta':         { en: 'Start ITR-2 Filing',      hi: 'ITR-2 भरना शुरू करें' , bn: 'ITR-2 দাখিল শুরু করুন', or: 'ITR-2 দাখিল শুরু', ta: 'ITR-2 தாக்கல் தொடங்குங்கள்', te: 'ITR-2 దాఖలు ప్రారంభించండి' },
  'itr2.cta_resume':  { en: 'Resume ITR-2 Filing',     hi: 'ITR-2 जारी रखें' , bn: 'ITR-2 দাখিল পুনরায় শুরু করুন', or: 'ITR-2 দাখিল', ta: 'ITR-2 தாக்கலை தொடரவும்', te: 'ITR-2 దాఖలు పున:ప్రారంభించండి' },
  'itr2.cta_view':    { en: 'View ITR-2 Result',       hi: 'ITR-2 परिणाम देखें' , bn: 'ITR-2 ফলাফল দেখুন', or: 'ITR-2 ফলাফল', ta: 'ITR-2 முடிவை பாருங்கள்', te: 'ITR-2 ఫలితం చూడండి' },

  // ── Quiz ────────────────────────────────────────────────────────────────────
  'quiz.title':              { en: 'Which ITR form should you file?', hi: 'आपको कौन सा ITR फॉर्म भरना चाहिए?', bn: 'আপনার কোন ITR ফর্ম দাখিল করা উচিত?', or: 'ଆପଣ କେଉଁ ITR ଫର୍ମ ଦାଖଲ କରିବା ଉଚିତ?', ta: 'நீங்கள் எந்த ITR படிவம் தாக்கல் செய்ய வேண்டும்?', te: 'మీరు ఏ ITR ఫారం దాఖలు చేయాలి?' },
  'quiz.subtitle':           { en: 'Answer a few quick questions — takes under 1 minute', hi: 'कुछ आसान सवालों के जवाब दें — 1 मिनट से कम लगता है', bn: 'কয়েকটি সহজ প্রশ্নের উত্তর দিন', or: 'କିଛି ସହଜ ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଅନ୍ତୁ', ta: 'சில எளிய கேள்விகளுக்கு பதில் சொல்லுங்கள்', te: 'కొన్ని సులభ ప్రశ్నలకు సమాధానం ఇవ్వండి' },
  // Q1-Q10 with plain-language hints for all levels
  'quiz.q1':  { en: 'Do you earn a salary from a job (and get a salary slip / Form-16)?', hi: 'क्या आप नौकरी से वेतन कमाते हैं (Form-16 मिलता है)?', bn: 'আপনি কি চাকরি থেকে বেতন পান (Form-16 আছে)?', or: 'ଆପଣ ଚାକିରିରୁ ବେତନ ପାଉଛନ୍ତି କି?', ta: 'நீங்கள் வேலையில் சம்பளம் பெறுகிறீர்களா?', te: 'మీరు జీతం సంపాదిస్తున్నారా (Form-16 ఉందా)?' },
  'quiz.q1_hint': { en: 'This includes private sector employees, government employees, and anyone whose employer deducts TDS from salary.', hi: 'इसमें सरकारी और निजी कर्मचारी दोनों शामिल हैं।', bn: 'সরকারি ও বেসরকারি কর্মচারী উভয়ই অন্তর্ভুক্ত।', or: 'ସରକାରୀ ଏବଂ ଘରୋଇ ଉଭୟ କର୍ମଚାରୀ ଅନ୍ତର୍ଭୁକ୍ତ।', ta: 'அரசு மற்றும் தனியார் ஊழியர்கள் இருவரும் உட்பட.', te: 'ప్రభుత్వ మరియు ప్రైవేట్ ఉద్యోగులు ఇద్దరూ వర్తిస్తారు.' },

  'quiz.q2':  { en: 'Did you buy or sell shares (stocks) or mutual funds this year?', hi: 'क्या इस साल शेयर या म्यूचुअल फंड खरीदा/बेचा?', bn: 'এই বছর কি শেয়ার বা মিউচুয়াল ফান্ড কিনেছেন বা বিক্রি করেছেন?', or: 'ଏହି ବର୍ଷ ଆପଣ ଶେୟାର ବା ମ୍ୟୁଚୁଆଲ ଫଣ୍ଡ କ୍ରୟ/ବିକ୍ରୟ କଲେ କି?', ta: 'இந்த ஆண்டு பங்குகள் அல்லது மியூச்சுவல் ஃபண்ட் வாங்கினீர்கள் அல்லது விற்றீர்களா?', te: 'ఈ సంవత్సరం స్టాక్స్ లేదా మ్యూచువల్ ఫండ్స్ కొన్నారా లేదా అమ్మారా?' },
  'quiz.q2_hint': { en: 'Includes Zerodha, Groww, Upstox, or any other broker. Even a single sale or SIP redemption counts.', hi: 'Zerodha, Groww, Upstox या किसी भी ब्रोकर का एक भी लेन-देन हो तो Yes।', bn: 'যেকোনো ব্রোকারের মাধ্যমে একটি ট্রেডও হলে Yes।', or: 'ଯେକୌଣସି ଏକ ଟ୍ରେଡ ହୋଇଥିଲେ Yes।', ta: 'எந்த ஒரு வர்த்தகமும் இருந்தாலும் Yes.', te: 'ఒక్క ట్రేడ్ అయినా ఉంటే Yes.' },

  'quiz.q3':  { en: 'Do you own a house or flat (even if you live in it)?', hi: 'क्या आपके पास कोई मकान या फ्लैट है (चाहे आप उसमें रहते हों)?', bn: 'আপনার কি বাড়ি বা ফ্ল্যাট আছে?', or: 'ଆପଣଙ୍କ ପାଖରେ ଘର ବା ଫ୍ଲ୍ୟାଟ ଅଛି କି?', ta: 'உங்களுக்கு வீடு அல்லது பிளாட் இருக்கிறதா?', te: 'మీకు ఇల్లు లేదా ఫ్లాట్ ఉందా?' },
  'quiz.q3_hint': { en: 'If you own a house property, you may need to declare it. If rented out, the rental income affects your form choice.', hi: 'मकान किराए पर है? तो ITR-2 फायदेमंद हो सकता है।', bn: 'বাড়ি ভাড়া দিলে ITR-2 প্রয়োজন হতে পারে।', or: 'ଘର ଭଡ଼ାରେ ଥିଲେ ITR-2 ଦরକার ହୋଇ ପାରେ।', ta: 'வீட்டை வாடகைக்கு விட்டிருந்தால் ITR-2 தேவைப்படலாம்.', te: 'ఇల్లు అద్దెకు ఇస్తే ITR-2 అవసరం.' },

  'quiz.q4':  { en: 'Do you have more than one house property (two flats, a plot + flat, etc.)?', hi: 'क्या आपके पास एक से अधिक मकान/प्रॉपर्टी है?', bn: 'আপনার কি একের বেশি বাড়ি বা সম্পত্তি আছে?', or: 'ଆପଣଙ୍କ ପାଖରେ ଏକରୁ ଅଧିକ ଘର ଅଛି କି?', ta: 'உங்களிடம் ஒன்றுக்கும் மேற்பட்ட வீடு இருக்கிறதா?', te: 'మీకు ఒకటి కంటే ఎక్కువ ఇళ్ళు ఉన్నాయా?' },
  'quiz.q4_hint': { en: 'If you own two or more properties (regardless of whether they are let out), you must file ITR-2.', hi: 'दो या अधिक प्रॉपर्टी होने पर ITR-2 अनिवार्य है।', bn: 'দুটি বা তার বেশি সম্পত্তি থাকলে ITR-2 বাধ্যতামূলক।', or: 'ଦୁଇ ବା ଅଧିକ ସମ୍ପତ୍ତି ଥିଲେ ITR-2 ଦାଖଲ କରିବା ଆବଶ୍ୟକ।', ta: 'இரண்டு அல்லது அதிகமான சொத்துக்கள் இருந்தால் ITR-2 கட்டாயம்.', te: 'రెండు లేదా అంతకంటే ఎక్కువ ఆస్తులు ఉంటే ITR-2 తప్పనిసరి.' },

  'quiz.q5':  { en: 'Is your total annual income more than ₹50 lakh (₹50,00,000)?', hi: 'क्या आपकी वार्षिक आय ₹50 लाख से अधिक है?', bn: 'আপনার বার্ষিক আয় কি ₹50 লক্ষের বেশি?', or: 'ଆପଣଙ୍କ ବାର୍ଷିକ ଆୟ ₹50 ଲକ୍ଷ ରୁ ଅଧିକ କି?', ta: 'உங்கள் வருடாந்திர வருமானம் ₹50 லட்சத்திற்கு மேல் உள்ளதா?', te: 'మీ వార్షిక ఆదాయం ₹50 లక్షలకు మించి ఉందా?' },
  'quiz.q5_hint': { en: 'Include all sources: salary, rent, capital gains, interest. If the combined total exceeds ₹50L, ITR-1 is not applicable.', hi: 'वेतन, किराया, ब्याज, सभी जोड़कर ₹50L से ज़्यादा? तो ITR-2।', bn: 'সব উৎস মিলিয়ে ₹50 লক্ষের বেশি হলে ITR-2।', or: 'ସମସ୍ତ ଆୟ ମିଳାଇ ₹50 ଲକ୍ଷ ରୁ ଅଧିକ ହେଲେ ITR-2।', ta: 'அனைத்து வருமானமும் சேர்த்து ₹50 லட்சத்திற்கு மேல் ஆனால் ITR-2.', te: 'అన్ని ఆదాయాలు కలిపి ₹50 లక్షలు దాటితే ITR-2.' },

  'quiz.q6':  { en: 'Do you have income or assets in a foreign country?', hi: 'क्या आपके पास विदेश में आय या संपत्ति है?', bn: 'আপনার কি বিদেশে আয় বা সম্পদ আছে?', or: 'ଆପଣଙ୍କ ବିଦେଶରେ ଆୟ ବା ସମ୍ପତ୍ତି ଅଛି କି?', ta: 'உங்களுக்கு வெளிநாட்டில் வருமானம் அல்லது சொத்து இருக்கிறதா?', te: 'మీకు విదేశాలలో ఆదాయం లేదా ఆస్తి ఉందా?' },
  'quiz.q6_hint': { en: 'Foreign salary, NRE/NRO accounts with foreign income, or any asset abroad — these require ITR-2 or higher.', hi: 'विदेशी वेतन, NRO/NRE खाते में विदेशी आय → ITR-2।', bn: 'বিদেশী বেতন বা NRO/NRE অ্যাকাউন্টে বিদেশী আয় → ITR-2।', or: 'ବିଦେଶ ବେତନ ବା ବୈଦେଶିକ ଆୟ ଥିଲେ ITR-2 ଦରକାର।', ta: 'வெளிநாட்டு ஊதியம் அல்லது சொத்து இருந்தால் ITR-2 தேவை.', te: 'విదేశీ జీతం లేదా ఆస్తి ఉంటే ITR-2 అవసరం.' },

  'quiz.q7':  { en: 'Do you run a business or work as a freelancer / consultant?', hi: 'क्या आप खुद का व्यवसाय करते हैं या फ्रीलांसर / कंसल्टेंट हैं?', bn: 'আপনি কি ব্যবসা করেন বা ফ্রিল্যান্সার / পরামর্শদাতা?', or: 'ଆପଣ ଏକ ବ୍ୟବସାୟ କରୁଛନ୍ତି ବା ଫ୍ରିଲ୍ୟାନ୍ସର?', ta: 'நீங்கள் வியாபாரம் நடத்துகிறீர்களா அல்லது ஃப்ரீலான்சர்?', te: 'మీరు వ్యాపారం నడుపుతున్నారా లేదా ఫ్రీలాన్సర్?' },
  'quiz.q7_hint': { en: 'Business/professional income (consulting, contracts, self-employment) requires ITR-3 or ITR-4, not ITR-1 or ITR-2. SmartTax does not currently support these.', hi: 'व्यापारिक/फ्रीलांस आय के लिए ITR-3/ITR-4 चाहिए — SmartTax अभी यह सपोर्ट नहीं करता।', bn: 'ব্যবসায়িক আয়ের জন্য ITR-3/ITR-4 প্রয়োজন।', or: 'ବ୍ୟବସାୟ ଆୟ ପାଇଁ ITR-3/ITR-4 ଦରକାର।', ta: 'வியாபார வருமானத்திற்கு ITR-3/ITR-4 தேவை.', te: 'వ్యాపార ఆదాయానికి ITR-3/ITR-4 అవసరం.' },

  'quiz.q8':  { en: 'Did you make any profit or loss from selling land or property?', hi: 'क्या आपने ज़मीन या मकान बेचकर कोई लाभ/हानि कमाई?', bn: 'আপনি কি জমি বা বাড়ি বিক্রি করে লাভ বা লোকসান করেছেন?', or: 'ଆପଣ ଜମି ବା ଘର ବିକ୍ରୟ କରି ଲାଭ/କ୍ଷତି ଅନୁଭବ କଲେ କି?', ta: 'நிலம் அல்லது வீட்டை விற்று லாபம் அல்லது நஷ்டம் ஏற்பட்டதா?', te: 'భూమి లేదా ఇల్లు అమ్మడం ద్వారా లాభం లేదా నష్టం ఏదైనా జరిగిందా?' },
  'quiz.q8_hint': { en: 'Capital gains from land, building, or property sale are reported in ITR-2 (Schedule CG). ITR-1 cannot include this.', hi: 'ज़मीन/मकान बेचने से लाभ → ITR-2 में Schedule CG भरना होगा।', bn: 'সম্পত্তি বিক্রয়ের লাভ → ITR-2 এ রিপোর্ট করতে হবে।', or: 'ସম୍ପତ୍ତି ବିକ୍ରୟ ଲାଭ → ITR-2 ରେ ରିପୋର୍ଟ ହୋଇଥାଏ।', ta: 'சொத்து விற்பனை லாபம் → ITR-2 இல் தெரிவிக்க வேண்டும்.', te: 'ఆస్తి అమ్మకం లాభం → ITR-2లో నివేదించాలి.' },

  'quiz.q9':  { en: 'Have you carried forward any losses from previous years?', hi: 'क्या आपके पिछले वर्षों की कोई हानि कैरी फॉरवर्ड है?', bn: 'আপনার কি আগের বছরের কোনো লোকসান ক্যারি ফরওয়ার্ড আছে?', or: 'ଆପଣଙ୍କ ପୂର୍ବ ବର୍ଷର କୌଣସି ଲୋକସାନ ଅଛି କି?', ta: 'கடந்த ஆண்டுகளின் நஷ்டங்களை முன்னோக்கி கொண்டு வந்தீர்களா?', te: 'గత సంవత్సరాల నష్టాలు ముందుకు తీసుకొచ్చారా?' },
  'quiz.q9_hint': { en: 'If you had losses from stocks or property in earlier years that you are setting off this year, you must file ITR-2.', hi: 'पिछले साल शेयर/प्रॉपर्टी लॉस कैरी फॉरवर्ड है? तो ITR-2।', bn: 'গত বছরের শেয়ার/সম্পত্তি ক্ষতি কিন্তু ITR-2 প্রয়োজন।', or: 'ପୂର୍ବ ଲୋକସାନ ଥିଲେ ITR-2 ଦାଖଲ ଅଗ୍ରବର୍ତ୍ତୀ।', ta: 'முந்தைய நஷ்டங்கள் இருந்தால் ITR-2 அவசியம்.', te: 'గత నష్టాలు ఉంటే ITR-2 అవసరం.' },

  'quiz.q10': { en: 'Apart from salary, do you have any other income — like interest, dividend, or freelance fees?', hi: 'वेतन के अलावा क्या ब्याज, डिविडेंड या फ्रीलांस आय है?', bn: 'বেতনের বাইরে সুদ, লভ্যাংশ বা অন্য আয় আছে?', or: 'ବେତନ ବ୍ୟତୀତ ଅଭ୍ୟାସ, ଲାଭାଂଶ ବା ଅନ୍ୟ ଆୟ ଅଛି?', ta: 'சம்பளத்தை தவிர வட்டி, டிவிடெண்ட் வருமானம் உள்ளதா?', te: 'జీతంతో పాటు వడ్డీ, డివిడెండ్ ఆదాయం ఉందా?' },
  'quiz.q10_hint': { en: 'Interest from savings/FD and dividends are allowed in ITR-1 (up to ₹50L total income). Freelance fees require ITR-3.', hi: 'बचत/FD पर ब्याज और डिविडेंड ITR-1 में दिखाए जा सकते हैं।', bn: 'FD সুদ ও লভ্যাংশ ITR-1 এ দেখানো যাবে।', or: 'FD ସୁଧ ଓ ଲାଭାଂଶ ITR-1 ରେ ଦର୍ଶାଯାଇ ପାରିବ।', ta: 'FD வட்டி மற்றும் டிவிடெண்ட் ITR-1 இல் காட்டலாம்.', te: 'FD వడ్డీ మరియు డివిడెండ్ ITR-1లో చూపవచ్చు.' },

  'quiz.yes':  { en: 'Yes', hi: 'हाँ', bn: 'হ্যাঁ', or: 'ହଁ', ta: 'ஆம்', te: 'అవును' },
  'quiz.no':   { en: 'No',  hi: 'नहीं', bn: 'না', or: 'ନା', ta: 'இல்லை', te: 'లేదు' },
  'quiz.result_itr1':         { en: 'You should file ITR-1', hi: 'आपको ITR-1 भरना चाहिए', bn: 'আপনাকে ITR-1 দাখিল করতে হবে', or: 'ଆପଣ ITR-1 ଦାଖଲ କରିବା ଉଚିତ', ta: 'நீங்கள் ITR-1 தாக்கல் செய்ய வேண்டும்', te: 'మీరు ITR-1 దాఖలు చేయాలి' },
  'quiz.result_itr2':         { en: 'You should file ITR-2', hi: 'आपको ITR-2 भरना चाहिए', bn: 'আপনাকে ITR-2 দাখিল করতে হবে', or: 'ଆପଣ ITR-2 ଦାଖଲ କରିବା ଉଚିତ', ta: 'நீங்கள் ITR-2 தாக்கல் செய்ய வேண்டும்', te: 'మీరు ITR-2 దాఖలు చేయాలి' },
  'quiz.result_neither':      { en: 'You may need ITR-3 or ITR-4', hi: 'आपको शायद ITR-3 या ITR-4 चाहिए', bn: 'আপনার ITR-3 বা ITR-4 প্রয়োজন হতে পারে', or: 'ଆପଣଙ୍କ ITR-3 ବା ITR-4 ଦରକାର ହୋଇ ପାରେ', ta: 'உங்களுக்கு ITR-3 அல்லது ITR-4 தேவைப்படலாம்', te: 'మీకు ITR-3 లేదా ITR-4 అవసరం కావచ్చు' },
  'quiz.result_itr1_reason':  { en: 'Your income is from salary only, with no capital gains or complex sources. ITR-1 (Sahaj) is the right form.', hi: 'आपकी आय केवल वेतन से है। ITR-1 (सहज) सही फॉर्म है।', bn: 'আপনার আয় শুধু বেতন থেকে। ITR-1 সঠিক ফর্ম।', or: 'ଆପଣଙ୍କ ଆୟ କେବଳ ବେତନରୁ। ITR-1 ସଠିକ ଫର୍ମ।', ta: 'உங்கள் வருமானம் சம்பளத்திலிருந்து மட்டும். ITR-1 சரியான படிவம்.', te: 'మీ ఆదాయం జీతం నుండి మాత్రమే. ITR-1 సరైన ఫారం.' },
  'quiz.result_itr2_reason':  { en: 'You have capital gains, multiple properties, or other complex income. ITR-2 covers all your sources accurately.', hi: 'आपके पास पूंजीगत लाभ या जटिल आय है। ITR-2 सभी आय को कवर करता है।', bn: 'আপনার মূলধনী লাভ বা জটিল আয় আছে। ITR-2 সব উৎস কভার করে।', or: 'ଆପଣଙ୍କ ପୁଞ୍ଜିଗତ ଲାଭ ବା ଜଟିଳ ଆୟ ଅଛି। ITR-2 ଉଚିତ।', ta: 'உங்களுக்கு முதலீட்டு லாபம் அல்லது சிக்கலான வருமானம் உள்ளது. ITR-2 சரி.', te: 'మీకు మూలధన లాభాలు లేదా సంక్లిష్ట ఆదాయం ఉంది. ITR-2 సరైనది.' },
  'quiz.result_neither_reason':{ en: 'Business or professional income needs ITR-3 or ITR-4, which SmartTax does not currently support. Please consult a CA or use the Income Tax portal directly.', hi: 'व्यापारिक आय के लिए ITR-3/ITR-4 चाहिए। कृपया CA से सलाह लें।', bn: 'ব্যবসায়িক আয়ের জন্য CA পরামর্শ নিন।', or: 'ବ୍ୟବସାୟ ଆୟ ପାଇଁ CA ଠାରୁ ପରାମର୍ଶ ନିଅନ୍ତୁ।', ta: 'வியாபார வருமானத்திற்கு CA ஆலோசனை பெறவும்.', te: 'వ్యాపార ఆదాయానికి CA సలహా తీసుకోండి.' },
  'quiz.consult_ca':          { en: 'Consult a CA →', hi: 'CA से सलाह लें →', bn: 'CA পরামর্শ নিন →', or: 'CA ପରାମର୍ଶ ନିଅନ୍ତୁ →', ta: 'CA ஆலோசனை பெறுங்கள் →', te: 'CA సలహా తీసుకోండి →' },
  'quiz.retake': { en: '← Retake quiz', hi: '← दोबारा लें', bn: '← পুনরায় নিন', or: '← ପୁଣି ନିଅନ୍ତୁ', ta: '← மீண்டும் எடுங்கள்', te: '← మళ్ళీ తీసుకోండి' },
  'quiz.close':  { en: 'Close', hi: 'बंद करें', bn: 'বন্ধ করুন', or: 'ବନ୍ଦ କରନ୍ତୁ', ta: 'மூடு', te: 'మూసివేయి' },

  // ── History ─────────────────────────────────────────────────────────────────
  'hist.title':          { en: 'Calculation History',          hi: 'गणना इतिहास' , bn: 'গণনার ইতিহাস', or: 'ଗଣନା ଇତିହାସ', ta: 'கணக்கீட்டு வரலாறு', te: 'లెక్కింపు చరిత్ర' },
  'hist.subtitle':       { en: 'All your saved tax calculations', hi: 'आपकी सभी सहेजी गई कर गणनाएँ' , bn: 'আপনার সমস্ত সংরক্ষিত কর গণনা', or: 'ଆପଣଙ୍କ ସମସ୍ତ ସଞ୍ଚୟ ହୋଇଥିବା ଆୟକର ଗଣନା', ta: 'உங்கள் சேமித்த வரி கணக்கீடுகள் அனைத்தும்', te: 'మీ సేవ్ చేసిన పన్ను లెక్కింపులన్నీ' },
  'hist.empty':          { en: 'No calculations saved yet',    hi: 'अभी तक कोई गणना सहेजी नहीं' , bn: 'এখনও কোনো গণনা সংরক্ষিত হয়নি', or: 'ଏখନ ପର୍ଯ୍ୟନ୍ତ କୌଣସି ଗଣନା ସଞ୍ଚୟ ହୋଇ ନାହିଁ', ta: 'இதுவரை கணக்கீடுகள் சேமிக்கப்படவில்லை', te: 'ఇంకా ఎటువంటి లెక్కింపులు సేవ్ కాలేదు' },
  'hist.empty_sub':      { en: 'Complete a tax calculation and it will appear here automatically.', hi: 'कर गणना पूरी करें, यह स्वतः यहाँ दिखेगी।' , bn: 'একটি কর গণনা সম্পন্ন করুন, এটি এখানে স্বয়ংক্রিয়ভাবে দেখাবে।', or: 'ଏକ ଆୟକର ଗଣନା ସମ୍ପୂର୍ଣ କରନ୍ତୁ, ଏହା ଏଠାରେ ସ୍ୱଯଂ ଦେଖାଯିବ।', ta: 'வரி கணக்கீடு முடித்தால் அது தானியங்கியாக இங்கு தோன்றும்.', te: 'పన్ను లెక్కింపు పూర్తి చేయండి, అది ఇక్కడ స్వయంచాలకంగా కనిపిస్తుంది.' },
  'hist.total_tax':      { en: 'Total Tax',      hi: 'कुल कर' , bn: 'মোট কর', or: 'ମୋଟ ଆୟକର', ta: 'மொத்த வரி', te: 'మొత్తం పన్ను' },
  'hist.refund':         { en: 'Refund Due',     hi: 'वापसी देय' , bn: 'ফেরত প্রাপ্য', or: 'ফেরত প্রাপ্য', ta: 'திரும்பப் பெற வேண்டியது', te: 'రিఫండ్ రావాల్సినది' },
  'hist.payable':        { en: 'Tax Payable',    hi: 'देय कर' , bn: 'প্রদেয় কর', or: 'ପ୍ରଦେୟ ଆୟକର', ta: 'செலுத்த வேண்டிய வரி', te: 'చెల్లించవలసిన పన్ను' },
  'hist.salary':         { en: 'Salary Tax',     hi: 'वेतन कर' , bn: 'বেতন কর', or: 'ବେତନ ଆୟକର', ta: 'சம்பள வரி', te: 'జీతం పన్ను' },
  'hist.stock':          { en: 'Stock Gains Tax',hi: 'शेयर लाभ कर' , bn: 'স্টক লাভ কর', or: 'ସ୍ଟକ ଲାଭ ଆୟକର', ta: 'பங்கு லாப வரி', te: 'స్టాక్ లాభం పన్ను' },
  'hist.mf':             { en: 'MF Equity Tax',  hi: 'म्यूचुअल फंड कर' , bn: 'মিউচুয়াল ফান্ড কর', or: 'ମ୍ୟୁଚୁଆଲ ଫଣ୍ଡ ଆୟକର', ta: 'மியூச்சுவல் ஃபண்ட் வரி', te: 'మ్యూచువల్ ఫండ్ పన్ను' },
  'hist.view':           { en: 'View Details',   hi: 'विवरण देखें' , bn: 'বিস্তারিত দেখুন', or: 'ବିବରଣ ଦେଖନ୍ତୁ', ta: 'விவரங்களை பாருங்கள்', te: 'వివరాలు చూడండి' },
  'hist.delete':         { en: 'Delete',         hi: 'हटाएँ' , bn: 'মুছুন', or: 'ବ୍ୟବହାର', ta: 'நீக்கு', te: 'తొలగించు' },
  'hist.confirm_delete': { en: 'Delete this entry?', hi: 'यह प्रविष्टि हटाएँ?' , bn: 'এই এন্ট্রি মুছবেন?', or: 'ଏହି ଏଣ୍ଟ୍ରି ଡିଲିଟ କରିବେ?', ta: 'இந்த பதிவை நீக்கவா?', te: 'ఈ ఎంట్రీని తొలగించాలా?' },
  'hist.confirm_delete_sub': { en: 'This cannot be undone.', hi: 'यह पूर्ववत नहीं किया जा सकता।' , bn: 'এটি পূর্বাবস্থায় ফেরানো যাবে না।', or: 'ଏହା ପୁନଃ ସ୍ଥାପନ ହୋଇ ପାରିବ ନାହିଁ।', ta: 'இதை மீண்டும் செய்ய முடியாது.', te: 'దీన్ని తిరిగి మార్చలేరు.' },

  // ── ITR-1 Salary ─────────────────────────────────────────────────────────────
  's1.title':         { en: 'Salary Income',          hi: 'वेतन आय' , bn: 'বেতন আয়', or: 'ବେତନ ଆୟ', ta: 'சம்பள வருமானம்', te: 'జీతం ఆదాయం' },
  's1.subtitle':      { en: 'Upload your Form-16 to extract salary details', hi: 'वेतन विवरण के लिए Form-16 अपलोड करें' , bn: 'বেতনের বিবরণ বের করতে Form-16 আপলোড করুন', or: 'ବେତନ ବିବରଣ ବାହାର କରିବା ପାଇଁ Form-16 ଅପଲୋଡ କରନ୍ତୁ', ta: 'சம்பள விவரங்களை பெற Form-16 பதிவேற்றவும்', te: 'జీతం వివరాలు తీయడానికి Form-16 అప్లోడ్ చేయండి' },
  's1.upload_label':  { en: 'Form-16 (PDF)',           hi: 'Form-16 (PDF)' , bn: 'Form-16 (PDF)', or: 'Form-16 (PDF)', ta: 'Form-16 (PDF)', te: 'Form-16 (PDF)' },
  's1.upload_desc':   { en: 'Upload your Form-16 PDF for automatic data extraction', hi: 'स्वचालित डेटा निकालने के लिए Form-16 PDF अपलोड करें' , bn: 'স্বয়ংক্রিয় তথ্য নিষ্কাশনের জন্য Form-16 PDF আপলোড করুন', or: 'ସ୍ୱୟଂଚାଳିତ ତଥ୍ୟ ଉଦ୍ଧାର ପାଇଁ Form-16 PDF ଅପଲୋଡ କରନ୍ତୁ', ta: 'தானியங்கி தரவு பிரித்தெடுக்க Form-16 PDF பதிவேற்றவும்', te: 'స్వయంచాలిత డేటా వెలికి తీయడానికి Form-16 PDF అప్లోడ్ చేయండి' },
  's1.parsing':       { en: 'Parsing document…',      hi: 'दस्तावेज़ पढ़ा जा रहा है…' , bn: 'নথি পড়া হচ্ছে…', or: 'ଡକ୍ୟୁମେଣ୍ଟ ପଢ଼ା ଯାଉଛି…', ta: 'ஆவணம் படிக்கப்படுகிறது…', te: 'పత్రం చదువుతోంది…' },
  's1.success':       { en: '✓ Form-16 uploaded successfully', hi: '✓ Form-16 सफलतापूर्वक अपलोड हुआ' , bn: '✓ Form-16 সফলভাবে আপলোড হয়েছে', or: '✓ Form-16 ସଫଳତାର ସହ ଅପଲୋଡ ହୋଇଛି', ta: '✓ Form-16 வெற்றிகரமாக பதிவேற்றப்பட்டது', te: '✓ Form-16 విజయవంతంగా అప్లోడ్ అయింది' },
  's1.continue_review': { en: 'Continue to Review →', hi: 'समीक्षा पर जाएं →' , bn: 'পর্যালোচনায় যান →', or: 'ପ୍ରତ୍ୟେକ ଦେଖିବା ଆଗ ଯାଆ →', ta: 'மதிப்பாய்வுக்கு தொடரவும் →', te: 'సమీక్షకు కొనసాగండి →' },

  // ── ITR-1 Review ─────────────────────────────────────────────────────────────
  'r1.title':         { en: 'Review Data',             hi: 'डेटा की समीक्षा करें' , bn: 'তথ্য পর্যালোচনা', or: 'ତଥ୍ୟ ସମୀକ୍ଷା', ta: 'தரவை மதிப்பாய்வு செய்யுங்கள்', te: 'డేటా సమీక్షించండి' },
  'r1.subtitle':      { en: 'Verify your information before calculating tax', hi: 'कर गणना से पहले जानकारी सत्यापित करें' , bn: 'কর গণনার আগে তথ্য যাচাই করুন', or: 'ଆୟକର ଗଣନା ପୂର୍ବରୁ ଆପଣଙ୍କ ତଥ୍ୟ ଯାଞ୍ଚ କରନ୍ତୁ', ta: 'வரி கணக்கிட முன் தகவலை சரிபார்க்கவும்', te: 'పన్ను లెక్కించే ముందు మీ సమాచారాన్ని ధృవీకరించండి' },
  'r1.salary_section':{ en: 'Salary Income',           hi: 'वेतन आय' , bn: 'বেতন আয়', or: 'ବେତନ ଆୟ', ta: 'சம்பள வருமானம்', te: 'జీతం ఆదాయం' },
  'r1.confirm':       { en: 'Confirm & Calculate →',   hi: 'पुष्टि करें और गणना करें →' , bn: 'নিশ্চিত করুন ও গণনা করুন →', or: 'ନିଶ୍ଚିତ କରି ଗଣନା କରନ୍ତୁ →', ta: 'உறுதிப்படுத்தி கணக்கிடுங்கள் →', te: 'నిర్ధారించి లెక్కించండి →' },
  'r1.edit_salary':   { en: '← Edit Salary',           hi: '← वेतन बदलें' , bn: '← বেতন সম্পাদনা করুন', or: '← ବେତନ ସম୍ପାଦନ', ta: '← சம்பளத்தை திருத்துங்கள்', te: '← జీతం మార్చండి' },
  'r1.incomplete':    { en: 'Please complete the Salary section first', hi: 'पहले वेतन अनुभाग पूरा करें' , bn: 'প্রথমে বেতন বিভাগটি সম্পন্ন করুন', or: 'ପ୍ରଥମେ ବେତନ ବିଭାଗ ସମ୍ପୂର୍ଣ କରନ୍ତୁ', ta: 'முதலில் சம்பள பிரிவை நிறைவு செய்யுங்கள்', te: 'ముందుగా జీతం విభాగాన్ని పూర్తి చేయండి' },
  'r1.go_salary':     { en: 'Go to Salary →',          hi: 'वेतन पर जाएं →' , bn: 'বেতন বিভাগে যান →', or: 'ବେতନ ବିଭାଗ ଯାଆ →', ta: 'சம்பள பிரிவுக்கு செல்லுங்கள் →', te: 'జీతం విభాగానికి వెళ్ళండి →' },

  // ── ITR-1 Calculate ──────────────────────────────────────────────────────────
  'c1.title':         { en: 'Final Tax Summary (New Regime)', hi: 'अंतिम कर सारांश (नई व्यवस्था)' , bn: 'চূড়ান্ত কর সারসংক্ষেপ (নতুন ব্যবস্থা)', or: 'ଅନ୍ତିମ ଆୟକର ସାରାଂଶ (ନୂଆ ବ୍ୟବସ୍ଥା)', ta: 'இறுதி வரி சுருக்கம் (புதிய முறை)', te: 'తుది పన్ను సారాంశం (కొత్త విధానం)' },
  'c1.last_calc':     { en: 'Last calculated:',         hi: 'अंतिम गणना:' , bn: 'শেষ গণনা:', or: 'ଶେଷ ଗଣନା:', ta: 'கடைசியாக கணக்கிடப்பட்டது:', te: 'చివరగా లెక్కించినది:' },
  'c1.salary_tax':    { en: 'Salary Tax (before cess)', hi: 'वेतन कर (सेस से पहले)' , bn: 'বেতন কর (সেস আগে)', or: 'ବେতନ ଆୟକର (ସେସ ପୂର୍ବରୁ)', ta: 'சம்பள வரி (சேஸ் முன்)', te: 'జీతం పన్ను (సెస్ ముందు)' },
  'c1.cess':          { en: 'Health & Education Cess (4%)', hi: 'स्वास्थ्य एवं शिक्षा उपकर (4%)' , bn: 'স্বাস্থ্য ও শিক্ষা সেস (৪%)', or: 'ସ୍ୱାସ୍ଥ୍ୟ ଓ ଶିକ୍ଷା ସେସ (4%)', ta: 'சுகாதார & கல்வி சேஸ் (4%)', te: 'ఆరోగ్యం & విద్య సెస్ (4%)' },
  'c1.total_liability':{ en: 'Total Tax Liability',     hi: 'कुल कर देयता' , bn: 'মোট কর দায়', or: 'মোট ক দ', ta: 'மொத்த வரி பொறுப்பு', te: 'మొత్తం పన్ను బాధ్యత' },
  'c1.refund':        { en: 'Refund Due:',              hi: 'वापसी देय:' , bn: 'ফেরত প্রাপ্য:', or: 'ফেরত প্রাপ্য:', ta: 'திரும்பப் பெற வேண்டியது:', te: 'రిఫండ్ రావాల్సినది:' },
  'c1.payable':       { en: 'Tax Payable:',             hi: 'देय कर:' , bn: 'প্রদেয় কর:', or: 'ପ୍ରଦେୟ ଆୟକର:', ta: 'செலுத்த வேண்டிய வரி:', te: 'చెల్లించవలసిన పన్ను:' },
  'c1.calculating':   { en: 'Calculating your tax…',   hi: 'आपकी कर गणना हो रही है…' , bn: 'আপনার কর গণনা হচ্ছে…', or: 'ଆପଣଙ୍କ ଆୟକର ଗଣନା ହୋଉଛି…', ta: 'உங்கள் வரி கணக்கிடப்படுகிறது…', te: 'మీ పన్ను లెక్కిస్తోంది…' },
  'c1.update':        { en: 'Update Calculation',       hi: 'गणना अपडेट करें' , bn: 'গণনা আপডেট করুন', or: 'ଗଣନା ଅଦ୍ୟତନ', ta: 'கணக்கீட்டை புதுப்பிக்கவும்', te: 'లెక్కింపు అప్డేట్ చేయండి' },
  'c1.recalculate':   { en: 'Recalculate',              hi: 'फिर से गणना करें' , bn: 'পুনরায় গণনা করুন', or: 'ପୁଣ ଗଣନା ଦ', ta: 'மீண்டும் கணக்கிடுங்கள்', te: 'మళ్ళీ లెక్కించండి' },
  'c1.back_review':   { en: '← Back to Review',        hi: '← समीक्षा पर वापस जाएं' , bn: '← পর্যালোচনায় ফিরুন', or: '← ସମୀକ୍ଷା ଉଭାବ ଫେরି', ta: '← மதிப்பாய்வுக்கு திரும்புங்கள்', te: '← సమీక్షకు తిరిగి వెళ్ళండి' },
  'c1.edit_salary':   { en: 'Edit Salary Details',      hi: 'वेतन विवरण बदलें' , bn: 'বেতনের বিবরণ সম্পাদনা করুন', or: 'ବେତନ ବିବରଣ ସମ୍ପାଦନ', ta: 'சம்பள விவரங்களை திருத்துங்கள்', te: 'జీతం వివరాలు మార్చండి' },
  'c1.no_result':     { en: 'No calculation result available', hi: 'कोई गणना परिणाम उपलब्ध नहीं' , bn: 'কোনো গণনার ফলাফল পাওয়া যায়নি', or: 'କୌଣସି ଗଣନା ଫଳ ଉପଲବ୍ଧ ନୁହେଁ', ta: 'கணக்கீட்டு முடிவு கிடைக்கவில்லை', te: 'లెక్కింపు ఫలితం అందుబాటులో లేదు' },
  'c1.calc_now':      { en: 'Calculate Now',            hi: 'अभी गणना करें' , bn: 'এখনই গণনা করুন', or: 'ଏବେ ଗଣନା', ta: 'இப்போதே கணக்கிடுங்கள்', te: 'ఇప్పుడే లెక్కించండి' },
  'c1.complete_first':{ en: 'Please complete and review your data first', hi: 'पहले अपना डेटा पूरा करें और समीक्षा करें' , bn: 'প্রথমে আপনার তথ্য সম্পন্ন করুন ও পর্যালোচনা করুন', or: 'ପ୍ରଥମେ ଡ଼ାଟ ସମ୍ପୂର୍ଣ କରି ସମୀକ୍ଷା', ta: 'முதலில் தரவை நிறைவு செய்து மதிப்பாய்வு செய்யுங்கள்', te: 'ముందుగా డేటా పూర్తి చేసి సమీక్షించండి' },
  'c1.go_review':     { en: 'Go to Review →',           hi: 'समीक्षा पर जाएं →' , bn: 'পর্যালোচনায় যান →', or: 'ସମୀକ୍ଷା ଯାଆ →', ta: 'மதிப்பாய்வுக்கு செல்லுங்கள் →', te: 'సమీక్షకు వెళ్ళండి →' },

  // ── ITR-2 Salary ─────────────────────────────────────────────────────────────
  's2.title':         { en: 'Salary Income',    hi: 'वेतन आय' , bn: 'বেতন আয়', or: 'ବେତନ ଆୟ', ta: 'சம்பள வருமானம்', te: 'జీతం ఆదాయం' },
  's2.subtitle':      { en: 'Upload your Form-16', hi: 'Form-16 अपलोड करें' , bn: 'আপনার Form-16 আপলোড করুন', or: 'ଆପଣଙ୍କ Form-16 ଅପଲୋଡ', ta: 'உங்கள் Form-16 பதிவேற்றவும்', te: 'మీ Form-16 అప్లోడ్ చేయండి' },
  's2.upload_label':  { en: 'Form-16 (PDF)',    hi: 'Form-16 (PDF)' , bn: 'Form-16 (PDF)', or: 'Form-16 (PDF)', ta: 'Form-16 (PDF)', te: 'Form-16 (PDF)' },
  's2.upload_desc':   { en: 'Upload your Form-16 PDF', hi: 'अपना Form-16 PDF अपलोड करें' , bn: 'আপনার Form-16 PDF আপলোড করুন', or: 'ଆପଣଙ୍କ Form-16 PDF ଅପଲୋଡ', ta: 'உங்கள் Form-16 PDF பதிவேற்றவும்', te: 'మీ Form-16 PDF అప్లోడ్ చేయండి' },
  's2.parsing':       { en: 'Parsing…',         hi: 'पढ़ा जा रहा है…' , bn: 'পড়া হচ্ছে…', or: 'ପଢ଼ା ଯାଉଛି…', ta: 'படிக்கப்படுகிறது…', te: 'చదువుతోంది…' },
  's2.success':       { en: '✓ Form-16 uploaded', hi: '✓ Form-16 अपलोड हुआ' , bn: '✓ Form-16 আপলোড হয়েছে', or: '✓ Form-16 ଅପଲୋଡ ହୋଇଛି', ta: '✓ Form-16 பதிவேற்றப்பட்டது', te: '✓ Form-16 అప్లోడ్ అయింది' },

  // ── ITR-2 Equity ─────────────────────────────────────────────────────────────
  'eq.title':         { en: 'Capital Gains',          hi: 'पूंजीगत लाभ' , bn: 'মূলধনী লাভ', or: 'ମୂଳଧନ ଲାଭ', ta: 'மூலதன ஆதாயம்', te: 'మూలధన లాభాలు' },
  'eq.subtitle':      { en: 'Upload your equity trades report from your broker', hi: 'अपने ब्रोकर से इक्विटी ट्रेड रिपोर्ट अपलोड करें' , bn: 'আপনার ব্রোকারের ইক্যুইটি ট্রেড রিপোর্ট আপলোড করুন', or: 'ଆପଣଙ୍କ ବ୍ରୋକର ରିପୋର୍ଟ ଅପଲୋଡ', ta: 'உங்கள் தரகரிடமிருந்து பங்கு வர்த்தக அறிக்கை பதிவேற்றவும்', te: 'మీ బ్రోకర్ నుండి ఈక్విటీ ట్రేడ్ రిపోర్ట్ అప్లోడ్ చేయండి' },
  'eq.broker_label':  { en: 'Select Broker',          hi: 'ब्रोकर चुनें' , bn: 'ব্রোকার নির্বাচন করুন', or: 'ବ୍ରୋକର ବ୍ୟବହାର', ta: 'தரகரை தேர்ந்தெடுங்கள்', te: 'బ్రోకర్ ఎంచుకోండి' },
  'eq.broker_hint_groww':   { en: 'Groww parser will be used to process your equity trades report', hi: 'Groww पार्सर आपकी इक्विटी रिपोर्ट प्रोसेस करेगा' , bn: 'Groww পার্সার আপনার ইক্যুইটি রিপোর্ট প্রক্রিয়া করবে', or: 'Groww ପାର୍ସର ଆପଣଙ୍କ ଇକ୍ୱିଟ ରିପୋର୍ଟ ପ୍ରକ୍ରିୟା', ta: 'Groww பார்சர் உங்கள் ஈக்விட்டி அறிக்கையை செயலாக்கும்', te: 'Groww పార్సర్ మీ ఈక్విటీ రిపోర్ట్ ప్రాసెస్ చేస్తుంది' },
  'eq.broker_hint_zerodha': { en: 'Zerodha parser will be used to process your equity trades report', hi: 'Zerodha पार्सर आपकी इक्विटी रिपोर्ट प्रोसेस करेगा' , bn: 'Zerodha পার্সার আপনার ইক্যুইটি রিপোর্ট প্রক্রিয়া করবে', or: 'Zerodha ପାର୍ସର ଆପଣଙ୍କ ଇକ୍ୱିଟ ରିପୋର୍ଟ ପ୍ରକ୍ରିୟା', ta: 'Zerodha பார்சர் உங்கள் ஈக்விட்டி அறிக்கையை செயலாக்கும்', te: 'Zerodha పార్సర్ మీ ఈక్విటీ రిపోర్ట్ ప్రాసెస్ చేస్తుంది' },
  'eq.upload_label':  { en: 'Equity Trades Report (Excel)', hi: 'इक्विटी ट्रेड रिपोर्ट (Excel)' , bn: 'ইক্যুইটি ট্রেড রিপোর্ট (Excel)', or: 'ଇକ୍ୱିଟ ଟ୍ରେଡ ରିପୋର୍ଟ (Excel)', ta: 'ஈக்விட்டி வர்த்தக அறிக்கை (Excel)', te: 'ఈక్విటీ ట్రేడ్ రిపోర్ట్ (Excel)' },
  'eq.parsing':       { en: 'Parsing report…',        hi: 'रिपोर्ट पढ़ी जा रही है…' , bn: 'রিপোর্ট পড়া হচ্ছে…', or: 'ରିପୋର୍ଟ ପଢ଼ା ଯାଉଛି…', ta: 'அறிக்கை படிக்கப்படுகிறது…', te: 'రిపోర్ట్ చదువుతోంది…' },
  'eq.success':       { en: 'Equity report uploaded successfully', hi: 'इक्विटी रिपोर्ट सफलतापूर्वक अपलोड हुई' , bn: 'ইক্যুইটি রিপোর্ট সফলভাবে আপলোড হয়েছে', or: 'ଇକ୍ୱିଟ ରିପୋର୍ଟ ସଫଳତାର ସହ ଅପଲୋଡ ହୋଇଛି', ta: 'ஈக்விட்டி அறிக்கை வெற்றிகரமாக பதிவேற்றப்பட்டது', te: 'ఈక్విటీ రిపోర్ట్ విజయవంతంగా అప్లోడ్ అయింది' },

  // ── ITR-2 Mutual Funds ───────────────────────────────────────────────────────
  'mf.title':         { en: 'Mutual Funds',     hi: 'म्यूचुअल फंड' , bn: 'মিউচুয়াল ফান্ড', or: 'ମ୍ୟୁଚୁଆଲ ଫଣ୍ଡ', ta: 'மியூச்சுவல் ஃபண்ட்', te: 'మ్యూచువల్ ఫండ్స్' },
  'mf.subtitle':      { en: 'Upload your mutual fund capital gains report', hi: 'म्यूचुअल फंड पूंजीगत लाभ रिपोर्ट अपलोड करें' , bn: 'মিউচুয়াল ফান্ড মূলধনী লাভ রিপোর্ট আপলোড করুন', or: 'ମ୍ୟୁଚୁଆଲ ଫଣ୍ଡ ଲାଭ ରିପୋର୍ଟ ଅପଲୋଡ', ta: 'மியூச்சுவல் ஃபண்ட் மூலதன ஆதாய அறிக்கை பதிவேற்றவும்', te: 'మ్యూచువల్ ఫండ్ మూలధన లాభాల రిపోర్ట్ అప్లోడ్ చేయండి' },
  'mf.upload_label':  { en: 'Mutual Fund Report (Excel)', hi: 'म्यूचुअल फंड रिपोर्ट (Excel)' , bn: 'মিউচুয়াল ফান্ড রিপোর্ট (Excel)', or: 'ମ୍ୟୁଚୁଆଲ ଫଣ୍ଡ ରିପୋର୍ଟ (Excel)', ta: 'மியூச்சுவல் ஃபண்ட் அறிக்கை (Excel)', te: 'మ్యూచువల్ ఫండ్ రిపోర్ట్ (Excel)' },
  'mf.upload_desc':   { en: 'Upload your mutual fund capital gains report in Excel or CSV format', hi: 'Excel या CSV फॉर्मेट में म्यूचुअल फंड रिपोर्ट अपलोड करें' , bn: 'Excel বা CSV ফরম্যাটে মিউচুয়াল ফান্ড রিপোর্ট আপলোড করুন', or: 'Excel ବା CSV ଫର୍ମାଟ ରିପୋର୍ଟ ଅପଲୋଡ', ta: 'Excel அல்லது CSV வடிவத்தில் மியூச்சுவல் ஃபண்ட் அறிக்கை பதிவேற்றவும்', te: 'Excel లేదా CSV ఫార్మాట్‌లో మ్యూచువల్ ఫండ్ రిపోర్ట్ అప్లోడ్ చేయండి' },
  'mf.parsing':       { en: 'Parsing mutual fund report…', hi: 'म्यूचुअल फंड रिपोर्ट पढ़ी जा रही है…' , bn: 'মিউচুয়াল ফান্ড রিপোর্ট পড়া হচ্ছে…', or: 'ମ୍ୟୁଚୁଆଲ ଫଣ୍ଡ ରିପୋର୍ଟ ପଢ଼ା ଯାଉଛି…', ta: 'மியூச்சுவல் ஃபண்ட் அறிக்கை படிக்கப்படுகிறது…', te: 'మ్యూచువల్ ఫండ్ రిపోర్ట్ చదువుతోంది…' },
  'mf.success':       { en: 'Mutual fund report uploaded successfully', hi: 'म्यूचुअल फंड रिपोर्ट सफलतापूर्वक अपलोड हुई' , bn: 'মিউচুয়াল ফান্ড রিপোর্ট সফলভাবে আপলোড হয়েছে', or: 'ମ୍ୟୁଚୁଆଲ ଫଣ୍ଡ ରିପୋର୍ଟ ସଫଳ', ta: 'மியூச்சுவல் ஃபண்ட் அறிக்கை வெற்றிகரமாக பதிவேற்றப்பட்டது', te: 'మ్యూచువల్ ఫండ్ రిపోర్ట్ విజయవంతంగా అప్లోడ్ అయింది' },

  // ── ITR-2 House Property ─────────────────────────────────────────────────────
  'hp.title':         { en: 'House Property Income',  hi: 'मकान संपत्ति आय' , bn: 'বাড়ির সম্পত্তির আয়', or: 'ଗୃହ ସମ୍ପତ୍ତି ଆୟ', ta: 'வீட்டு சொத்து வருமானம்', te: 'ఇల్లు ఆస్తి ఆదాయం' },
  'hp.subtitle':      { en: 'Add all properties you own. Under the New Tax Regime, HP losses cannot be set off against salary — only carried forward 8 years (intra-head).', hi: 'अपनी सभी संपत्तियाँ जोड़ें। नई कर व्यवस्था में HP हानि को वेतन के विरुद्ध समायोजित नहीं किया जा सकता — केवल 8 वर्ष तक आगे ले जाया जा सकता है।' , bn: 'Add all properties you own. Under the New Tax Regime, HP losses cannot be set off against salary — only carried forward 8 years (intra-head).', or: 'Add all properties you own. Under the New Tax Regime, HP losses cannot be set off against salary — only carried forward 8 years (intra-head).', ta: 'Add all properties you own. Under the New Tax Regime, HP losses cannot be set off against salary — only carried forward 8 years (intra-head).', te: 'Add all properties you own. Under the New Tax Regime, HP losses cannot be set off against salary — only carried forward 8 years (intra-head).' },
  'hp.add_another':   { en: '+ Add Another Property', hi: '+ एक और संपत्ति जोड़ें' , bn: '+ আরেকটি সম্পত্তি যোগ করুন', or: '+ ଆଉ ଏକ ସମ୍ପତ୍ତ ଯୋ', ta: '+ மற்றொரு சொத்தை சேர்க்கவும்', te: '+ మరో ఆస్తి జోడించండి' },
  'hp.skip':          { en: 'Skip — no house property', hi: 'छोड़ें — कोई मकान संपत्ति नहीं' , bn: 'এড়িয়ে যান — বাড়ি নেই', or: 'ଏଡ଼ ❥ ଘ ନ', ta: 'தவிர்க்கவும் — வீடு இல்லை', te: 'వదలండి — ఇల్లు లేదు' },
  'hp.calc_continue': { en: 'Calculate & Continue →', hi: 'गणना करें और जारी रखें →' , bn: 'গণনা ও চালিয়ে যান →', or: 'ଗଣନ ଓ ଜାରି →', ta: 'கணக்கிட்டு தொடரவும் →', te: 'లెక్కించి కొనసాగండి →' },
  'hp.calculating':   { en: 'Calculating…',           hi: 'गणना हो रही है…' , bn: 'গণনা হচ্ছে…', or: 'ଗଣନ ହ…', ta: 'கணக்கிடப்படுகிறது…', te: 'లెక్కిస్తోంది…' },
  'hp.net_income':    { en: 'Net HP Income (added to taxable income)', hi: 'शुद्ध HP आय (कर योग्य आय में जुड़ती है)' , bn: 'নিট HP আয় (করযোগ্য আয়ে যোগ হবে)', or: 'ଶୁ HP ଆୟ', ta: 'நிகர HP வருமானம் (வரிக்கு சேர்க்கப்படும்)', te: 'నికర HP ఆదాయం (పన్ను ఆదాయానికి చేరుతుంది)' },
  'hp.total_loss':    { en: 'Total HP Loss (carry forward)', hi: 'कुल HP हानि (आगे ले जाएं)' , bn: 'মোট HP ক্ষতি (ক্যারি ফরওয়ার্ড)', or: 'ମୋଟ HP କ୍ଷତ', ta: 'மொத்த HP இழப்பு (முன்னோக்கி கொண்டு செல்லவும்)', te: 'మొత్తం HP నష్టం (ముందుకు తీసుకెళ్ళండి)' },
  'hp.prop_type':     { en: 'Property Type',          hi: 'संपत्ति प्रकार' , bn: 'সম্পত্তির ধরন', or: 'ସ ପ ବ', ta: 'சொத்தின் வகை', te: 'ఆస్తి రకం' },
  'hp.remove':        { en: 'Remove',                 hi: 'हटाएँ' , bn: 'সরান', or: 'ହ', ta: 'நீக்கு', te: 'తొలగించు' },
  'hp.preview':       { en: 'Preview This Property',  hi: 'इस संपत्ति का पूर्वावलोकन करें' , bn: 'এই সম্পত্তি প্রিভিউ করুন', or: 'ଏ ସ ପ', ta: 'இந்த சொத்தை முன்னோட்டம் பாருங்கள்', te: 'ఈ ఆస్తి ప్రివ్యూ చూడండి' },
  'hp.sop_label':     { en: 'Self-Occupied',          hi: 'स्वयं-अधिकृत' , bn: 'নিজে বাস করেন', or: 'ନ ର', ta: 'சொந்தமாக குடியிருக்கிறீர்கள்', te: 'స్వయంగా నివాసం' },
  'hp.sop_hint':      { en: 'You live in this property', hi: 'आप इस संपत्ति में रहते हैं' , bn: 'আপনি এই সম্পত্তিতে বাস করেন', or: 'ଆ ଏ ସ ର', ta: 'நீங்கள் இந்த சொத்தில் வசிக்கிறீர்கள்', te: 'మీరు ఈ ఆస్తిలో నివసిస్తున్నారు' },
  'hp.lop_label':     { en: 'Let Out',                hi: 'किराए पर दी गई' , bn: 'ভাড়া দেওয়া', or: 'ଭ ଦ', ta: 'வாடகைக்கு விட்டீர்கள்', te: 'అద్దెకు ఇచ్చారు' },
  'hp.lop_hint':      { en: 'Rented out to a tenant', hi: 'किरायेदार को किराए पर दी गई' , bn: 'ভাড়াটিয়াকে ভাড়া দেওয়া', or: 'ଭ ର', ta: 'வாடகைதாரருக்கு வாடகைக்கு விட்டீர்கள்', te: 'అద్దెదారుకు అద్దెకు ఇచ్చారు' },
  'hp.dlop_label':    { en: 'Deemed Let Out',         hi: 'मानी गई किराए पर' , bn: 'গণ্য ভাড়া দেওয়া', or: 'ମ ଭ', ta: 'கணக்கீடு வாடகைக்கு விட்டது', te: 'పరిగణించబడిన అద్దె' },
  'hp.dlop_hint':     { en: '2+ houses — treated as rented', hi: '2+ मकान — किराए पर मानी जाती है' , bn: '২+ বাড়ি — ভাড়া হিসেবে গণ্য', or: '2+ ଘ ❥ ଭ', ta: '2+ வீடுகள் — வாடகையாக கருதப்படும்', te: '2+ ఇళ్ళు — అద్దెగా పరిగణించబడుతుంది' },
  'hp.sop_warning':   { en: 'New Tax Regime: Self-occupied property has NAV = ₹0. No home loan interest deduction (Sec 24b) is allowed.', hi: 'नई कर व्यवस्था: स्वयं-अधिकृत संपत्ति का NAV = ₹0। Sec 24b के तहत गृह ऋण ब्याज कटौती नहीं मिलती।' , bn: 'New Tax Regime: Self-occupied property has NAV = ₹0. No home loan interest deduction (Sec 24b) is allowed.', or: 'New Tax Regime: Self-occupied property has NAV = ₹0. No home loan interest deduction (Sec 24b) is allowed.', ta: 'New Tax Regime: Self-occupied property has NAV = ₹0. No home loan interest deduction (Sec 24b) is allowed.', te: 'New Tax Regime: Self-occupied property has NAV = ₹0. No home loan interest deduction (Sec 24b) is allowed.' },
  'hp.gross_rent':    { en: 'Gross Rent Received (Annual)', hi: 'प्राप्त सकल किराया (वार्षिक)' , bn: 'মোট ভাড়া প্রাপ্তি (বার্ষিক)', or: 'ମ ଭ', ta: 'மொத்த வாடகை (ஆண்டு)', te: 'స్థూల అద్దె (వార్షిక)' },
  'hp.market_rent':   { en: 'Expected Market / Municipal Value', hi: 'अपेक्षित बाज़ार/नगर पालिका मूल्य' , bn: 'প্রত্যাশিত বাজার / পৌর মূল্য', or: 'ବ ମ', ta: 'எதிர்பார்க்கப்படும் சந்தை / நகராட்சி மதிப்பு', te: 'ఆశించిన మార్కెట్ / పురపాలక విలువ' },
  'hp.gav_hint_lop':  { en: 'GAV = higher of actual rent or market rent', hi: 'GAV = वास्तविक किराया या बाज़ार किराया, जो अधिक हो' , bn: 'GAV = higher of actual rent or market rent', or: 'GAV = higher of actual rent or market rent', ta: 'GAV = higher of actual rent or market rent', te: 'GAV = higher of actual rent or market rent' },
  'hp.gav_hint_dlop': { en: 'GAV for Deemed Let-Out = this value', hi: 'मानी गई संपत्ति का GAV = यह मूल्य' , bn: 'GAV for Deemed Let-Out = this value', or: 'GAV for Deemed Let-Out = this value', ta: 'GAV for Deemed Let-Out = this value', te: 'GAV for Deemed Let-Out = this value' },
  'hp.municipal_tax': { en: 'Municipal Taxes Paid',   hi: 'नगर पालिका कर भुगतान' , bn: 'পৌর কর প্রদান', or: 'ପ ক', ta: 'நகராட்சி வரி செலுத்தப்பட்டது', te: 'పురపాలక పన్నులు చెల్లించారు' },
  'hp.municipal_hint':{ en: 'Only if paid by owner (not tenant)', hi: 'केवल यदि मालिक ने भुगतान किया हो (किरायेदार ने नहीं)' , bn: 'Only if paid by owner (not tenant)', or: 'Only if paid by owner (not tenant)', ta: 'Only if paid by owner (not tenant)', te: 'Only if paid by owner (not tenant)' },
  'hp.loan_interest': { en: 'Home Loan Interest — Sec 24(b)', hi: 'गृह ऋण ब्याज — Sec 24(b)' , bn: 'গৃহঋণের সুদ — Sec 24(b)', or: 'ଗ ଋ — Sec 24(b)', ta: 'வீட்டுக்கடன் வட்டி — Sec 24(b)', te: 'హోమ్ లోన్ వడ్డీ — Sec 24(b)' },
  'hp.loan_hint':     { en: 'Fully deductible for Let-Out / Deemed Let-Out', hi: 'किराए पर दी गई संपत्ति के लिए पूर्णतः कटौती योग्य' , bn: 'Fully deductible for Let-Out / Deemed Let-Out', or: 'Fully deductible for Let-Out / Deemed Let-Out', ta: 'Fully deductible for Let-Out / Deemed Let-Out', te: 'Fully deductible for Let-Out / Deemed Let-Out' },
  'hp.breakdown':     { en: 'Breakdown',              hi: 'विवरण' , bn: 'বিবরণ', or: 'ବ', ta: 'விவரம்', te: 'వివరాలు' },
  'hp.gav':           { en: 'Gross Annual Value (GAV)', hi: 'सकल वार्षिक मूल्य (GAV)' , bn: 'মোট বার্ষিক মূল্য (GAV)', or: 'ମ ব GAV', ta: 'மொத்த வருடாந்திர மதிப்பு (GAV)', te: 'స్థూల వార్షిక విలువ (GAV)' },
  'hp.less_muni':     { en: 'Less: Municipal Taxes',  hi: 'घटाएं: नगर पालिका कर' , bn: 'কম: পৌর কর', or: 'ক ப', ta: 'கழித்தல்: நகராட்சி வரி', te: 'తగ్గించు: పురపాలక పన్నులు' },
  'hp.nav':           { en: 'Net Annual Value (NAV)',  hi: 'शुद्ध वार्षिक मूल्य (NAV)' , bn: 'নিট বার্ষিক মূল্য (NAV)', or: 'ش NAV', ta: 'நிகர வருடாந்திர மதிப்பு (NAV)', te: 'నికర వార్షిక విలువ (NAV)' },
  'hp.std_dedn':      { en: 'Less: 30% Standard Deduction (Sec 24a)', hi: 'घटाएं: 30% मानक कटौती (Sec 24a)' , bn: 'কম: ৩০% মানক ছাড় (Sec 24a)', or: 'ক 30% Sec 24a', ta: 'கழித்தல்: 30% நிலையான விலக்கு (Sec 24a)', te: 'తగ్గించు: 30% ప్రమాణ తగ్గింపు (Sec 24a)' },
  'hp.interest_dedn': { en: 'Less: Home Loan Interest (Sec 24b)', hi: 'घटाएं: गृह ऋण ब्याज (Sec 24b)' , bn: 'কম: গৃহঋণের সুদ (Sec 24b)', or: 'ক Sec 24b', ta: 'கழித்தல்: வீட்டுக்கடன் வட்டி (Sec 24b)', te: 'తగ్గించు: హోమ్ లోన్ వడ్డీ (Sec 24b)' },
  'hp.hp_income':     { en: 'HP Income',              hi: 'HP आय' , bn: 'HP আয়', or: 'HP ❥', ta: 'HP வருமானம்', te: 'HP ఆదాయం' },
  'hp.hp_loss':       { en: 'HP Loss',                hi: 'HP हानि' , bn: 'HP ক্ষতি', or: 'HP ❥', ta: 'HP இழப்பு', te: 'HP నష్టం' },
  'hp.no_setoff':     { en: '✗ Cannot set-off against Salary under New Regime', hi: '✗ नई व्यवस्था में वेतन के विरुद्ध समायोजन नहीं' , bn: '✗ Cannot set-off against Salary under New Regime', or: '✗ Cannot set-off against Salary under New Regime', ta: '✗ Cannot set-off against Salary under New Regime', te: '✗ Cannot set-off against Salary under New Regime' },
  'hp.carry_fwd':     { en: '↷ Carry forward {n} years (intra-head only)', hi: '↷ {n} वर्ष आगे ले जाएं (केवल HP आय के विरुद्ध)' , bn: '↷ Carry forward {n} years (intra-head only)', or: '↷ Carry forward {n} years (intra-head only)', ta: '↷ Carry forward {n} years (intra-head only)', te: '↷ Carry forward {n} years (intra-head only)' },

  // ── ITR-2 Review ─────────────────────────────────────────────────────────────
  'r2.title':         { en: 'Review Data',     hi: 'डेटा की समीक्षा' , bn: 'তথ্য পর্যালোচনা', or: 'ତଥ୍ୟ ସମୀକ୍ଷା', ta: 'தரவை மதிப்பாய்வு செய்யுங்கள்', te: 'డేటా సమీక్షించండి' },
  'r2.subtitle':      { en: 'Verify all information before calculating tax', hi: 'कर गणना से पहले सभी जानकारी सत्यापित करें' , bn: 'কর গণনার আগে সমস্ত তথ্য যাচাই করুন', or: 'ক গ আগে সব তথ্য যাচাই', ta: 'வரி கணக்கிட முன் அனைத்து தகவலையும் சரிபார்க்கவும்', te: 'పన్ను లెక్కించే ముందు అన్ని సమాచారాన్ని ధృవీకరించండి' },
  'r2.salary':        { en: 'Salary Income',   hi: 'वेतन आय' , bn: 'বেতন আয়', or: 'ବେତନ ଆୟ', ta: 'சம்பள வருமானம்', te: 'జీతం ఆదాయం' },
  'r2.equity':        { en: 'Equity Gains',    hi: 'इक्विटी लाभ' , bn: 'ইক্যুইটি লাভ', or: 'ই ল', ta: 'ஈக்விட்டி ஆதாயம்', te: 'ఈక్విటీ లాభాలు' },
  'r2.mf':            { en: 'Mutual Fund Gains', hi: 'म्यूचुअल फंड लाभ' , bn: 'মিউচুয়াল ফান্ড লাভ', or: 'মিউ ফান্ড লাভ', ta: 'மியூச்சுவல் ஃபண்ட் ஆதாயம்', te: 'మ్యూచువల్ ఫండ్ లాభాలు' },
  'r2.hp':            { en: 'House Property',  hi: 'मकान संपत्ति' , bn: 'বাড়ির সম্পত্তি', or: 'ଗ ସ', ta: 'வீட்டு சொத்து', te: 'ఇల్లు ఆస్తి' },
  'r2.no_hp':         { en: 'No house property added. Click "Add" to include property income/loss.', hi: 'कोई संपत्ति नहीं जोड़ी। संपत्ति आय/हानि जोड़ने के लिए "जोड़ें" पर क्लिक करें।' , bn: 'No house property added. Click "Add" to include property income/loss.', or: 'No house property added. Click "Add" to include property income/loss.', ta: 'No house property added. Click "Add" to include property income/loss.', te: 'No house property added. Click "Add" to include property income/loss.' },
  'r2.stcg_before':   { en: 'STCG (before Jul 23)',   hi: 'STCG (23 जुलाई से पहले)' , bn: 'STCG (before Jul 23)', or: 'STCG (before Jul 23)', ta: 'STCG (before Jul 23)', te: 'STCG (before Jul 23)' },
  'r2.stcg_after':    { en: 'STCG (after Jul 23)',    hi: 'STCG (23 जुलाई के बाद)' , bn: 'STCG (after Jul 23)', or: 'STCG (after Jul 23)', ta: 'STCG (after Jul 23)', te: 'STCG (after Jul 23)' },
  'r2.ltcg_before':   { en: 'LTCG (before Jul 23)',   hi: 'LTCG (23 जुलाई से पहले)' , bn: 'LTCG (before Jul 23)', or: 'LTCG (before Jul 23)', ta: 'LTCG (before Jul 23)', te: 'LTCG (before Jul 23)' },
  'r2.ltcg_after':    { en: 'LTCG (after Jul 23)',    hi: 'LTCG (23 जुलाई के बाद)' , bn: 'LTCG (after Jul 23)', or: 'LTCG (after Jul 23)', ta: 'LTCG (after Jul 23)', te: 'LTCG (after Jul 23)' },
  'r2.eq_stcg':       { en: 'Equity STCG',   hi: 'इक्विटी STCG' , bn: 'Equity STCG', or: 'Equity STCG', ta: 'Equity STCG', te: 'Equity STCG' },
  'r2.eq_ltcg':       { en: 'Equity LTCG',   hi: 'इक्विटी LTCG' , bn: 'Equity LTCG', or: 'Equity LTCG', ta: 'Equity LTCG', te: 'Equity LTCG' },
  'r2.debt_stcg':     { en: 'Debt STCG',     hi: 'डेट STCG' , bn: 'Debt STCG', or: 'Debt STCG', ta: 'Debt STCG', te: 'Debt STCG' },
  'r2.debt_ltcg':     { en: 'Debt LTCG',     hi: 'डेट LTCG' , bn: 'Debt LTCG', or: 'Debt LTCG', ta: 'Debt LTCG', te: 'Debt LTCG' },
  'r2.net_hp_income': { en: 'Net HP income added to taxable income:', hi: 'कर योग्य आय में जुड़ी शुद्ध HP आय:' , bn: 'Net HP income added to taxable income:', or: 'Net HP income added to taxable income:', ta: 'Net HP income added to taxable income:', te: 'Net HP income added to taxable income:' },
  'r2.total_hp_loss': { en: 'Total HP loss (carry forward):', hi: 'कुल HP हानि (आगे ले जाने योग्य):' , bn: 'Total HP loss (carry forward):', or: 'Total HP loss (carry forward):', ta: 'Total HP loss (carry forward):', te: 'Total HP loss (carry forward):' },
  'r2.carry_fwd':     { en: 'Carry forward {n} years (cannot set off against salary)', hi: '{n} वर्ष आगे ले जाएं (वेतन के विरुद्ध समायोजन नहीं)' , bn: 'Carry forward {n} years (cannot set off against salary)', or: 'Carry forward {n} years (cannot set off against salary)', ta: 'Carry forward {n} years (cannot set off against salary)', te: 'Carry forward {n} years (cannot set off against salary)' },
  'r2.self_occ':      { en: 'Self-Occupied', hi: 'स्वयं-अधिकृत' , bn: 'নিজে বাস করেন', or: 'ନ ର', ta: 'சொந்தமாக குடியிருக்கிறீர்கள்', te: 'స్వయంగా నివాసం' },
  'r2.let_out':       { en: 'Let Out',       hi: 'किराए पर दी गई' , bn: 'ভাড়া দেওয়া', or: 'ଭ ଦ', ta: 'வாடகைக்கு விட்டீர்கள்', te: 'అద్దెకు ఇచ్చారు' },
  'r2.deemed':        { en: 'Deemed Let Out',hi: 'मानी गई किराए पर' , bn: 'গণ্য ভাড়া দেওয়া', or: 'ମ ଭ', ta: 'கணக்கீடு வாடகைக்கு விட்டது', te: 'పరిగణించబడిన అద్దె' },
  'r2.edit_data':     { en: '← Edit Data',  hi: '← डेटा बदलें' , bn: '← তথ্য সম্পাদনা করুন', or: '← ত স', ta: '← தரவை திருத்துங்கள்', te: '← డేటా మార్చండి' },
  'r2.confirm':       { en: 'Confirm & Calculate →', hi: 'पुष्टि करें और गणना करें →' , bn: 'নিশ্চিত করুন ও গণনা করুন →', or: 'ନିଶ୍ଚିତ କରି ଗଣନା କରନ୍ତୁ →', ta: 'உறுதிப்படுத்தி கணக்கிடுங்கள் →', te: 'నిర్ధారించి లెక్కించండి →' },
  'r2.incomplete':    { en: 'Please complete the Salary section first', hi: 'पहले वेतन अनुभाग पूरा करें' , bn: 'প্রথমে বেতন বিভাগটি সম্পন্ন করুন', or: 'ପ୍ରଥମେ ବେତନ ବିଭାଗ ସମ୍ପୂର୍ଣ କରନ୍ତୁ', ta: 'முதலில் சம்பள பிரிவை நிறைவு செய்யுங்கள்', te: 'ముందుగా జీతం విభాగాన్ని పూర్తి చేయండి' },
  'r2.go_salary':     { en: 'Go to Salary →', hi: 'वेतन पर जाएं →' , bn: 'বেতন বিভাগে যান →', or: 'ବେতନ ବିଭାଗ ଯାଆ →', ta: 'சம்பள பிரிவுக்கு செல்லுங்கள் →', te: 'జీతం విభాగానికి వెళ్ళండి →' },

  // ── ITR-2 Calculate ──────────────────────────────────────────────────────────
  'c2.title':               { en: 'Your Tax Summary',              hi: 'आपका कर सारांश' , bn: 'আপনার কর সারসংক্ষেপ', or: 'ਆ ক স', ta: 'உங்கள் வரி சுருக்கம்', te: 'మీ పన్ను సారాంశం' },
  'c2.subtitle':            { en: 'FY 2024–25 · New Tax Regime · ITR-2', hi: 'वित्त वर्ष 2024–25 · नई कर व्यवस्था · ITR-2' , bn: 'FY 2024–25 · New Tax Regime · ITR-2', or: 'FY 2024–25 · New Tax Regime · ITR-2', ta: 'FY 2024–25 · New Tax Regime · ITR-2', te: 'FY 2024–25 · New Tax Regime · ITR-2' },
  'c2.total_tax':           { en: 'Total Tax Liability',           hi: 'कुल कर देयता' , bn: 'মোট কর দায়', or: 'মোট ক দ', ta: 'மொத்த வரி பொறுப்பு', te: 'మొత్తం పన్ను బాధ్యత' },
  'c2.incl_cess':           { en: 'incl. 4% cess',                hi: 'सहित 4% उपकर' , bn: 'incl. 4% cess', or: 'incl. 4% cess', ta: 'incl. 4% cess', te: 'incl. 4% cess' },
  'c2.eff_rate':            { en: 'Effective Tax Rate',            hi: 'प्रभावी कर दर' , bn: 'Effective Tax Rate', or: 'Effective Tax Rate', ta: 'Effective Tax Rate', te: 'Effective Tax Rate' },
  'c2.on_taxable':          { en: 'on taxable income',            hi: 'कर योग्य आय पर' , bn: 'on taxable income', or: 'on taxable income', ta: 'on taxable income', te: 'on taxable income' },
  'c2.tds_paid':            { en: 'TDS Already Paid',             hi: 'पहले से भुगतान TDS' , bn: 'TDS Already Paid', or: 'TDS Already Paid', ta: 'TDS Already Paid', te: 'TDS Already Paid' },
  'c2.tds_employer':        { en: 'deducted by employer (Form-16)', hi: 'नियोक्ता द्वारा काटा गया (Form-16)' , bn: 'deducted by employer (Form-16)', or: 'deducted by employer (Form-16)', ta: 'deducted by employer (Form-16)', te: 'deducted by employer (Form-16)' },
  'c2.tds_vs_tax':          { en: 'TDS vs Tax Due',               hi: 'TDS बनाम देय कर' , bn: 'TDS vs Tax Due', or: 'TDS vs Tax Due', ta: 'TDS vs Tax Due', te: 'TDS vs Tax Due' },
  'c2.tax_liability':       { en: 'Tax Liability',                hi: 'कर देयता' , bn: 'Tax Liability', or: 'Tax Liability', ta: 'Tax Liability', te: 'Tax Liability' },
  'c2.refund_bank':         { en: 'Will be credited to your bank account', hi: 'आपके बैंक खाते में जमा होगा' , bn: 'Will be credited to your bank account', or: 'Will be credited to your bank account', ta: 'Will be credited to your bank account', te: 'Will be credited to your bank account' },
  'c2.payable_challan':     { en: 'Pay via Challan 280 before filing', hi: 'दाखिल करने से पहले Challan 280 से भुगतान करें' , bn: 'Pay via Challan 280 before filing', or: 'Pay via Challan 280 before filing', ta: 'Pay via Challan 280 before filing', te: 'Pay via Challan 280 before filing' },
  'c2.excess':              { en: 'Excess:',                      hi: 'अतिरिक्त:' , bn: 'Excess:', or: 'Excess:', ta: 'Excess:', te: 'Excess:' },
  'c2.still_pay':           { en: 'Still to pay:',               hi: 'अभी भाकी:' , bn: 'Still to pay:', or: 'Still to pay:', ta: 'Still to pay:', te: 'Still to pay:' },
  'c2.where_from':          { en: 'Where your tax comes from',   hi: 'आपका कर कहाँ से आता है' , bn: 'Where your tax comes from', or: 'Where your tax comes from', ta: 'Where your tax comes from', te: 'Where your tax comes from' },
  'c2.salary_debt':         { en: 'Salary + Debt MF',            hi: 'वेतन + डेट MF' , bn: 'Salary + Debt MF', or: 'Salary + Debt MF', ta: 'Salary + Debt MF', te: 'Salary + Debt MF' },
  'c2.slab_tax':            { en: 'slab tax',                    hi: 'स्लैब कर' , bn: 'slab tax', or: 'slab tax', ta: 'slab tax', te: 'slab tax' },
  'c2.stock_gains':         { en: 'Equity Stock Gains',          hi: 'इक्विटी शेयर लाभ' , bn: 'Equity Stock Gains', or: 'Equity Stock Gains', ta: 'Equity Stock Gains', te: 'Equity Stock Gains' },
  'c2.eq_mf':               { en: 'Equity Mutual Funds',         hi: 'इक्विटी म्यूचुअल फंड' , bn: 'Equity Mutual Funds', or: 'Equity Mutual Funds', ta: 'Equity Mutual Funds', te: 'Equity Mutual Funds' },
  'c2.stcg_ltcg':           { en: 'STCG + LTCG',                hi: 'STCG + LTCG' , bn: 'STCG + LTCG', or: 'STCG + LTCG', ta: 'STCG + LTCG', te: 'STCG + LTCG' },
  'c2.subtotal':            { en: 'Sub-total (before cess)',      hi: 'उप-योग (सेस से पहले)' , bn: 'Sub-total (before cess)', or: 'Sub-total (before cess)', ta: 'Sub-total (before cess)', te: 'Sub-total (before cess)' },
  'c2.cess_line':           { en: '+ Health & Education Cess (4%)', hi: '+ स्वास्थ्य एवं शिक्षा उपकर (4%)' , bn: '+ Health & Education Cess (4%)', or: '+ Health & Education Cess (4%)', ta: '+ Health & Education Cess (4%)', te: '+ Health & Education Cess (4%)' },
  'c2.salary_section':      { en: 'Salary income → taxable income → tax', hi: 'वेतन → कर योग्य आय → कर' , bn: 'Salary income → taxable income → tax', or: 'Salary income → taxable income → tax', ta: 'Salary income → taxable income → tax', te: 'Salary income → taxable income → tax' },
  'c2.new_regime_note':     { en: 'Under the New Tax Regime, you get a flat ₹75,000 standard deduction. No 80C/HRA/NPS deductions are available.', hi: 'नई कर व्यवस्था में ₹75,000 की मानक कटौती मिलती है। 80C/HRA/NPS कटौती उपलब्ध नहीं है।' , bn: 'Under the New Tax Regime, you get a flat ₹75,000 standard deduction. No 80C/HRA/NPS deductions are available.', or: 'Under the New Tax Regime, you get a flat ₹75,000 standard deduction. No 80C/HRA/NPS deductions are available.', ta: 'Under the New Tax Regime, you get a flat ₹75,000 standard deduction. No 80C/HRA/NPS deductions are available.', te: 'Under the New Tax Regime, you get a flat ₹75,000 standard deduction. No 80C/HRA/NPS deductions are available.' },
  'c2.gross_salary':        { en: 'Gross Salary (Form-16)',       hi: 'सकल वेतन (Form-16)' , bn: 'Gross Salary (Form-16)', or: 'Gross Salary (Form-16)', ta: 'Gross Salary (Form-16)', te: 'Gross Salary (Form-16)' },
  'c2.std_dedn':            { en: 'Less: Standard Deduction (Sec 16)', hi: 'घटाएं: मानक कटौती (Sec 16)' , bn: 'Less: Standard Deduction (Sec 16)', or: 'Less: Standard Deduction (Sec 16)', ta: 'Less: Standard Deduction (Sec 16)', te: 'Less: Standard Deduction (Sec 16)' },
  'c2.add_hp':              { en: 'Add: Net House Property Income', hi: 'जोड़ें: शुद्ध HP आय' , bn: 'Add: Net House Property Income', or: 'Add: Net House Property Income', ta: 'Add: Net House Property Income', te: 'Add: Net House Property Income' },
  'c2.add_debt':            { en: 'Add: Debt MF Gains (treated as income)', hi: 'जोड़ें: डेट MF लाभ (आय माना गया)' , bn: 'Add: Debt MF Gains (treated as income)', or: 'Add: Debt MF Gains (treated as income)', ta: 'Add: Debt MF Gains (treated as income)', te: 'Add: Debt MF Gains (treated as income)' },
  'c2.taxable_income':      { en: 'Taxable Income (Salary Head)', hi: 'कर योग्य आय (वेतन मद)' , bn: 'Taxable Income (Salary Head)', or: 'Taxable Income (Salary Head)', ta: 'Taxable Income (Salary Head)', te: 'Taxable Income (Salary Head)' },
  'c2.slabs_title':         { en: 'New Regime Slabs',             hi: 'नई व्यवस्था के स्लैब' , bn: 'New Regime Slabs', or: 'New Regime Slabs', ta: 'New Regime Slabs', te: 'New Regime Slabs' },
  'c2.rebate_87a':          { en: '✓ Section 87A Rebate applied — income ≤ ₹12,00,000, full tax waived', hi: '✓ धारा 87A छूट लागू — आय ≤ ₹12,00,000, पूरा कर माफ' , bn: '✓ Section 87A Rebate applied — income ≤ ₹12,00,000, full tax waived', or: '✓ Section 87A Rebate applied — income ≤ ₹12,00,000, full tax waived', ta: '✓ Section 87A Rebate applied — income ≤ ₹12,00,000, full tax waived', te: '✓ Section 87A Rebate applied — income ≤ ₹12,00,000, full tax waived' },
  'c2.salary_tax_row':      { en: 'Tax on Salary + Debt MF (before cess)', hi: 'वेतन + डेट MF पर कर (सेस से पहले)' , bn: 'Tax on Salary + Debt MF (before cess)', or: 'Tax on Salary + Debt MF (before cess)', ta: 'Tax on Salary + Debt MF (before cess)', te: 'Tax on Salary + Debt MF (before cess)' },
  'c2.equity_section':      { en: 'Equity stocks — capital gains tax', hi: 'इक्विटी शेयर — पूंजीगत लाभ कर' , bn: 'Equity stocks — capital gains tax', or: 'Equity stocks — capital gains tax', ta: 'Equity stocks — capital gains tax', te: 'Equity stocks — capital gains tax' },
  'c2.equity_note':         { en: 'Tax rates changed on July 23, 2024 (Budget 2024). STCG: 15% → 20%; LTCG: 10% → 12.5%. Your gains are split by date.', hi: '23 जुलाई 2024 को कर दरें बदलीं (बजट 2024)। STCG: 15% → 20%; LTCG: 10% → 12.5%। आपका लाभ तारीख के अनुसार बंटा है।' , bn: 'Tax rates changed on July 23, 2024 (Budget 2024). STCG: 15% → 20%; LTCG: 10% → 12.5%. Your gains are split by date.', or: 'Tax rates changed on July 23, 2024 (Budget 2024). STCG: 15% → 20%; LTCG: 10% → 12.5%. Your gains are split by date.', ta: 'Tax rates changed on July 23, 2024 (Budget 2024). STCG: 15% → 20%; LTCG: 10% → 12.5%. Your gains are split by date.', te: 'Tax rates changed on July 23, 2024 (Budget 2024). STCG: 15% → 20%; LTCG: 10% → 12.5%. Your gains are split by date.' },
  'c2.stcg_before':         { en: 'STCG — before Jul 23, 2024',   hi: 'STCG — 23 जुलाई 2024 से पहले' , bn: 'STCG — before Jul 23, 2024', or: 'STCG — before Jul 23, 2024', ta: 'STCG — before Jul 23, 2024', te: 'STCG — before Jul 23, 2024' },
  'c2.stcg_after':          { en: 'STCG — after Jul 23, 2024',    hi: 'STCG — 23 जुलाई 2024 के बाद' , bn: 'STCG — after Jul 23, 2024', or: 'STCG — after Jul 23, 2024', ta: 'STCG — after Jul 23, 2024', te: 'STCG — after Jul 23, 2024' },
  'c2.ltcg_before':         { en: 'LTCG — before Jul 23, 2024',   hi: 'LTCG — 23 जुलाई 2024 से पहले' , bn: 'LTCG — before Jul 23, 2024', or: 'LTCG — before Jul 23, 2024', ta: 'LTCG — before Jul 23, 2024', te: 'LTCG — before Jul 23, 2024' },
  'c2.ltcg_after':          { en: 'LTCG — after Jul 23, 2024',    hi: 'LTCG — 23 जुलाई 2024 के बाद' , bn: 'LTCG — after Jul 23, 2024', or: 'LTCG — after Jul 23, 2024', ta: 'LTCG — after Jul 23, 2024', te: 'LTCG — after Jul 23, 2024' },
  'c2.stcg_tax':            { en: 'STCG Tax',    hi: 'STCG कर' , bn: 'STCG Tax', or: 'STCG Tax', ta: 'STCG Tax', te: 'STCG Tax' },
  'c2.ltcg_tax':            { en: 'LTCG Tax',    hi: 'LTCG कर' , bn: 'LTCG Tax', or: 'LTCG Tax', ta: 'LTCG Tax', te: 'LTCG Tax' },
  'c2.total_stock_tax':     { en: 'Total Equity Stock Tax', hi: 'कुल इक्विटी शेयर कर' , bn: 'Total Equity Stock Tax', or: 'Total Equity Stock Tax', ta: 'Total Equity Stock Tax', te: 'Total Equity Stock Tax' },
  'c2.mf_section':          { en: 'Mutual funds — capital gains tax', hi: 'म्यूचुअल फंड — पूंजीगत लाभ कर' , bn: 'Mutual funds — capital gains tax', or: 'Mutual funds — capital gains tax', ta: 'Mutual funds — capital gains tax', te: 'Mutual funds — capital gains tax' },
  'c2.mf_note':             { en: 'Equity MFs are taxed separately (STCG 20%, LTCG 12.5% after ₹1.25L exemption). Debt MFs (post Apr 2023) are added to income and taxed at your slab rate.', hi: 'इक्विटी MF पर अलग से कर (STCG 20%, LTCG 12.5% ₹1.25 लाख छूट के बाद)। डेट MF (अप्रैल 2023 के बाद) आय में जोड़े जाते हैं।' , bn: 'Equity MFs are taxed separately (STCG 20%, LTCG 12.5% after ₹1.25L exemption). Debt MFs (post Apr 2023) are added to income and taxed at your slab rate.', or: 'Equity MFs are taxed separately (STCG 20%, LTCG 12.5% after ₹1.25L exemption). Debt MFs (post Apr 2023) are added to income and taxed at your slab rate.', ta: 'Equity MFs are taxed separately (STCG 20%, LTCG 12.5% after ₹1.25L exemption). Debt MFs (post Apr 2023) are added to income and taxed at your slab rate.', te: 'Equity MFs are taxed separately (STCG 20%, LTCG 12.5% after ₹1.25L exemption). Debt MFs (post Apr 2023) are added to income and taxed at your slab rate.' },
  'c2.eq_mf_stcg':          { en: 'Equity MF — STCG',    hi: 'इक्विटी MF — STCG' , bn: 'Equity MF — STCG', or: 'Equity MF — STCG', ta: 'Equity MF — STCG', te: 'Equity MF — STCG' },
  'c2.eq_mf_ltcg':          { en: 'Equity MF — LTCG',    hi: 'इक्विटी MF — LTCG' , bn: 'Equity MF — LTCG', or: 'Equity MF — LTCG', ta: 'Equity MF — LTCG', te: 'Equity MF — LTCG' },
  'c2.ltcg_exemption':      { en: 'Less: LTCG Exemption (Sec 112A)', hi: 'घटाएं: LTCG छूट (Sec 112A)' , bn: 'Less: LTCG Exemption (Sec 112A)', or: 'Less: LTCG Exemption (Sec 112A)', ta: 'Less: LTCG Exemption (Sec 112A)', te: 'Less: LTCG Exemption (Sec 112A)' },
  'c2.taxable_eq_ltcg':     { en: 'Taxable Equity MF LTCG', hi: 'कर योग्य इक्विटी MF LTCG' , bn: 'Taxable Equity MF LTCG', or: 'Taxable Equity MF LTCG', ta: 'Taxable Equity MF LTCG', te: 'Taxable Equity MF LTCG' },
  'c2.eq_mf_tax':           { en: 'Equity MF Tax',        hi: 'इक्विटी MF कर' , bn: 'Equity MF Tax', or: 'Equity MF Tax', ta: 'Equity MF Tax', te: 'Equity MF Tax' },
  'c2.debt_stcg':           { en: 'Debt MF — STCG',       hi: 'डेट MF — STCG' , bn: 'Debt MF — STCG', or: 'Debt MF — STCG', ta: 'Debt MF — STCG', te: 'Debt MF — STCG' },
  'c2.debt_ltcg':           { en: 'Debt MF — LTCG',       hi: 'डेट MF — LTCG' , bn: 'Debt MF — LTCG', or: 'Debt MF — LTCG', ta: 'Debt MF — LTCG', te: 'Debt MF — LTCG' },
  'c2.debt_added':          { en: 'Total added to Salary income', hi: 'कुल वेतन आय में जोड़ा गया' , bn: 'Total added to Salary income', or: 'Total added to Salary income', ta: 'Total added to Salary income', te: 'Total added to Salary income' },
  'c2.hp_section':          { en: 'House property income / loss', hi: 'मकान संपत्ति आय / हानि' , bn: 'House property income / loss', or: 'House property income / loss', ta: 'House property income / loss', te: 'House property income / loss' },
  'c2.hp_note':             { en: 'Under the New Regime, only positive HP income is added to your taxable income. HP losses cannot be set off against salary — only carried forward 8 years against future HP income.', hi: 'नई व्यवस्था में केवल सकारात्मक HP आय कर योग्य आय में जुड़ती है। HP हानि वेतन के विरुद्ध नहीं — केवल 8 वर्ष तक HP आय के विरुद्ध आगे ले जाई जा सकती है।' , bn: 'Under the New Regime, only positive HP income is added to your taxable income. HP losses cannot be set off against salary — only carried forward 8 years against future HP income.', or: 'Under the New Regime, only positive HP income is added to your taxable income. HP losses cannot be set off against salary — only carried forward 8 years against future HP income.', ta: 'Under the New Regime, only positive HP income is added to your taxable income. HP losses cannot be set off against salary — only carried forward 8 years against future HP income.', te: 'Under the New Regime, only positive HP income is added to your taxable income. HP losses cannot be set off against salary — only carried forward 8 years against future HP income.' },
  'c2.hp_net_added':        { en: 'Net HP Income added to taxable income', hi: 'कर योग्य आय में जुड़ी शुद्ध HP आय' , bn: 'Net HP Income added to taxable income', or: 'Net HP Income added to taxable income', ta: 'Net HP Income added to taxable income', te: 'Net HP Income added to taxable income' },
  'c2.hp_loss_carry':       { en: 'Total HP Loss (carry forward only)', hi: 'कुल HP हानि (केवल आगे ले जाने योग्य)' , bn: 'Total HP Loss (carry forward only)', or: 'Total HP Loss (carry forward only)', ta: 'Total HP Loss (carry forward only)', te: 'Total HP Loss (carry forward only)' },
  'c2.final_section':       { en: 'Final tax reconciliation', hi: 'अंतिम कर मिलान' , bn: 'Final tax reconciliation', or: 'Final tax reconciliation', ta: 'Final tax reconciliation', te: 'Final tax reconciliation' },
  'c2.salary_row':          { en: 'Tax on Salary + Debt MF', hi: 'वेतन + डेट MF पर कर' , bn: 'Tax on Salary + Debt MF', or: 'Tax on Salary + Debt MF', ta: 'Tax on Salary + Debt MF', te: 'Tax on Salary + Debt MF' },
  'c2.stock_row':           { en: 'Tax on Equity Stock Gains', hi: 'इक्विटी शेयर लाभ पर कर' , bn: 'Tax on Equity Stock Gains', or: 'Tax on Equity Stock Gains', ta: 'Tax on Equity Stock Gains', te: 'Tax on Equity Stock Gains' },
  'c2.mf_row':              { en: 'Tax on Equity Mutual Funds', hi: 'इक्विटी म्यूचुअल फंड पर कर' , bn: 'Tax on Equity Mutual Funds', or: 'Tax on Equity Mutual Funds', ta: 'Tax on Equity Mutual Funds', te: 'Tax on Equity Mutual Funds' },
  'c2.cess_row':            { en: 'Health & Education Cess (4%)', hi: 'स्वास्थ्य एवं शिक्षा उपकर (4%)' , bn: 'স্বাস্থ্য ও শিক্ষা সেস (৪%)', or: 'ସ୍ୱାସ୍ଥ୍ୟ ଓ ଶିକ୍ଷା ସେସ (4%)', ta: 'சுகாதார & கல்வி சேஸ் (4%)', te: 'ఆరోగ్యం & విద్య సెస్ (4%)' },
  'c2.less_tds':            { en: 'Less: TDS Already Deducted (Form-16)', hi: 'घटाएं: पहले से काटा TDS (Form-16)' , bn: 'Less: TDS Already Deducted (Form-16)', or: 'Less: TDS Already Deducted (Form-16)', ta: 'Less: TDS Already Deducted (Form-16)', te: 'Less: TDS Already Deducted (Form-16)' },
  'c2.refund_label':        { en: 'Refund Due to You',   hi: 'आपको वापसी देय' , bn: 'Refund Due to You', or: 'Refund Due to You', ta: 'Refund Due to You', te: 'Refund Due to You' },
  'c2.payable_label':       { en: 'Balance Tax Payable',  hi: 'शेष देय कर' , bn: 'Balance Tax Payable', or: 'Balance Tax Payable', ta: 'Balance Tax Payable', te: 'Balance Tax Payable' },
  'c2.challan_tip':         { en: 'Pay via Challan 280 on the Income Tax e-filing portal before submitting your ITR to avoid interest charges under Sec 234B / 234C.', hi: 'Sec 234B/234C के तहत ब्याज से बचने के लिए ITR जमा करने से पहले Income Tax e-filing पोर्टल पर Challan 280 से भुगतान करें।' , bn: 'Pay via Challan 280 on the Income Tax e-filing portal before submitting your ITR to avoid interest charges under Sec 234B / 234C.', or: 'Pay via Challan 280 on the Income Tax e-filing portal before submitting your ITR to avoid interest charges under Sec 234B / 234C.', ta: 'Pay via Challan 280 on the Income Tax e-filing portal before submitting your ITR to avoid interest charges under Sec 234B / 234C.', te: 'Pay via Challan 280 on the Income Tax e-filing portal before submitting your ITR to avoid interest charges under Sec 234B / 234C.' },
  'c2.refund_tip':          { en: 'Your refund will be credited to your pre-validated bank account after ITR processing — typically within 30–45 days of filing.', hi: 'आपका रिफंड ITR प्रोसेसिंग के बाद आपके पूर्व-सत्यापित बैंक खाते में जमा होगा — आमतौर पर दाखिल करने के 30–45 दिनों में।' , bn: 'Your refund will be credited to your pre-validated bank account after ITR processing — typically within 30–45 days of filing.', or: 'Your refund will be credited to your pre-validated bank account after ITR processing — typically within 30–45 days of filing.', ta: 'Your refund will be credited to your pre-validated bank account after ITR processing — typically within 30–45 days of filing.', te: 'Your refund will be credited to your pre-validated bank account after ITR processing — typically within 30–45 days of filing.' },
  'c2.back_review':         { en: '← Back to Review',  hi: '← समीक्षा पर वापस' , bn: '← পর্যালোচনায় ফিরুন', or: '← ସମୀକ୍ଷା ଉଭାବ ଫେরି', ta: '← மதிப்பாய்வுக்கு திரும்புங்கள்', te: '← సమీక్షకు తిరిగి వెళ్ళండి' },
  'c2.edit_salary':         { en: 'Edit Salary',        hi: 'वेतन बदलें' , bn: 'বেতন সম্পাদনা', or: 'বেতন সম্পাদনা', ta: 'சம்பளத்தை திருத்து', te: 'జీతం మార్చు' },
  'c2.edit_equity':         { en: 'Edit Equity',        hi: 'इक्विटी बदलें' , bn: 'ইক্যুইটি সম্পাদনা', or: 'ইক্যুইটি সম্পাদনা', ta: 'ஈக்விட்டியை திருத்து', te: 'ఈక్విటీ మార్చు' },
  'c2.edit_mf':             { en: 'Edit MF',            hi: 'MF बदलें' , bn: 'MF সম্পাদনা', or: 'MF সম্পাদনা', ta: 'MF திருத்து', te: 'MF మార్చు' },
  'c2.edit_hp':             { en: 'Edit HP',            hi: 'HP बदलें' , bn: 'HP সম্পাদনা', or: 'HP সম্পাদনা', ta: 'HP திருத்து', te: 'HP మార్చు' },
  'c2.complete_first':      { en: 'Please complete and review your data first', hi: 'पहले अपना डेटा पूरा करें और समीक्षा करें' , bn: 'প্রথমে আপনার তথ্য সম্পন্ন করুন ও পর্যালোচনা করুন', or: 'ପ୍ରଥମେ ଡ଼ାଟ ସମ୍ପୂର୍ଣ କରି ସମୀକ୍ଷା', ta: 'முதலில் தரவை நிறைவு செய்து மதிப்பாய்வு செய்யுங்கள்', te: 'ముందుగా డేటా పూర్తి చేసి సమీక్షించండి' },
  'c2.go_review':           { en: 'Go to Review →',    hi: 'समीक्षा पर जाएं →' , bn: 'পর্যালোচনায় যান →', or: 'ସମୀକ୍ଷା ଯାଆ →', ta: 'மதிப்பாய்வுக்கு செல்லுங்கள் →', te: 'సమీక్షకు వెళ్ళండి →' },
  'c2.calculating':         { en: 'Calculating your tax liability…', hi: 'आपकी कर देयता की गणना हो रही है…' , bn: 'আপনার কর দায় গণনা হচ্ছে…', or: 'আ ক দ গ…', ta: 'உங்கள் வரி பொறுப்பு கணக்கிடப்படுகிறது…', te: 'మీ పన్ను బాధ్యత లెక్కిస్తోంది…' },
  'c2.applying_rules':      { en: 'Applying FY 2024-25 New Tax Regime rules', hi: 'वित्त वर्ष 2024-25 नई कर व्यवस्था के नियम लागू हो रहे हैं' , bn: 'FY 2024-25 নতুন কর নিয়ম প্রয়োগ হচ্ছে', or: 'FY 2024-25 নতুন কর নিয়ম', ta: 'FY 2024-25 புதிய வரி முறை விதிகள் பயன்படுத்தப்படுகின்றன', te: 'FY 2024-25 కొత్త పన్ను విధాన నిబంధనలు వర్తిస్తున్నాయి' },
  'c2.no_result':           { en: 'No calculation result yet', hi: 'अभी कोई परिणाम नहीं' , bn: 'এখনও কোনো গণনার ফলাফল নেই', or: 'এখনও ফলাফল নেই', ta: 'இன்னும் கணக்கீட்டு முடிவு இல்லை', te: 'ఇంకా లెక్కింపు ఫలితం లేదు' },
  'c2.calc_now':            { en: 'Calculate Now',      hi: 'अभी गणना करें' , bn: 'এখনই গণনা করুন', or: 'ଏବେ ଗଣନା', ta: 'இப்போதே கணக்கிடுங்கள்', te: 'ఇప్పుడే లెక్కించండి' },
  'c2.retry':               { en: 'Retry Calculation',  hi: 'दोबारा गणना करें' , bn: 'পুনরায় গণনা করুন', or: 'পুনরায় গণনা', ta: 'மீண்டும் கணக்கிடுங்கள்', te: 'మళ్ళీ లెక్కించండి' },
  'c2.self_occ':            { en: 'Self-Occupied',      hi: 'स्वयं-अधिकृत' , bn: 'নিজে বাস করেন', or: 'ନ ର', ta: 'சொந்தமாக குடியிருக்கிறீர்கள்', te: 'స్వయంగా నివాసం' },
  'c2.let_out':             { en: 'Let Out',            hi: 'किराए पर दी गई' , bn: 'ভাড়া দেওয়া', or: 'ଭ ଦ', ta: 'வாடகைக்கு விட்டீர்கள்', te: 'అద్దెకు ఇచ్చారు' },
  'c2.deemed_let_out':      { en: 'Deemed Let Out',     hi: 'मानी गई किराए पर' , bn: 'গণ্য ভাড়া দেওয়া', or: 'ମ ଭ', ta: 'கணக்கீடு வாடகைக்கு விட்டது', te: 'పరిగణించబడిన అద్దె' },
  'c2.loss_carry':          { en: 'Loss of {amt} cannot be set off against salary · Carry forward {n} years', hi: '{amt} की हानि वेतन के विरुद्ध समायोजित नहीं — {n} वर्ष आगे ले जाएं' , bn: 'Loss of {amt} cannot be set off against salary · Carry forward {n} years', or: 'Loss of {amt} cannot be set off against salary · Carry forward {n} years', ta: 'Loss of {amt} cannot be set off against salary · Carry forward {n} years', te: 'Loss of {amt} cannot be set off against salary · Carry forward {n} years' },
  'c2.gav':                 { en: 'GAV:',               hi: 'GAV:' , bn: 'GAV:', or: 'GAV:', ta: 'GAV:', te: 'GAV:' },
  'c2.muni_tax':            { en: 'Municipal taxes:',   hi: 'नगर पालिका कर:' , bn: 'Municipal taxes:', or: 'Municipal taxes:', ta: 'Municipal taxes:', te: 'Municipal taxes:' },
  'c2.nav':                 { en: 'NAV:',               hi: 'NAV:' , bn: 'NAV:', or: 'NAV:', ta: 'NAV:', te: 'NAV:' },
  'c2.std_dedn30':          { en: 'Std deduction (30%):',hi: 'मानक कटौती (30%):' , bn: 'Std deduction (30%):', or: 'Std deduction (30%):', ta: 'Std deduction (30%):', te: 'Std deduction (30%):' },
  'c2.loan_int':            { en: 'Home loan interest Sec 24(b):', hi: 'गृह ऋण ब्याज Sec 24(b):' , bn: 'Home loan interest Sec 24(b):', or: 'Home loan interest Sec 24(b):', ta: 'Home loan interest Sec 24(b):', te: 'Home loan interest Sec 24(b):' },

  // ── Info page ────────────────────────────────────────────────────────────────
  'info.title':             { en: 'How tax is calculated',  hi: 'कर की गणना कैसे होती है' , bn: 'কর কিভাবে গণনা হয়', or: 'ক কিভাবে', ta: 'வரி எப்படி கணக்கிடப்படுகிறது', te: 'పన్ను ఎలా లెక్కించబడుతుంది' },
  'info.subtitle':          { en: 'A clear explanation of how SmartTax computes your tax under the New Tax Regime (FY 2024–25).', hi: 'SmartTax नई कर व्यवस्था (वित्त वर्ष 2024–25) के तहत कर की गणना कैसे करता है, इसकी स्पष्ट व्याख्या।' , bn: 'A clear explanation of how SmartTax computes your tax under the New Tax Regime (FY 2024–25).', or: 'A clear explanation of how SmartTax computes your tax under the New Tax Regime (FY 2024–25).', ta: 'A clear explanation of how SmartTax computes your tax under the New Tax Regime (FY 2024–25).', te: 'A clear explanation of how SmartTax computes your tax under the New Tax Regime (FY 2024–25).' },
  'info.salary_title':      { en: 'Salary income',          hi: 'वेतन आय' , bn: 'Salary income', or: 'Salary income', ta: 'Salary income', te: 'Salary income' },
  'info.std_dedn_title':    { en: 'Standard deduction',     hi: 'मानक कटौती' , bn: 'মানক কাটছাঁট', or: 'মানক কাটছাঁট', ta: 'நிலையான விலக்கு', te: 'ప్రమాణ తగ్గింపు' },
  'info.std_dedn_desc':     { en: 'A flat deduction of ₹75,000 is applied to your gross salary.', hi: 'आपके सकल वेतन से ₹75,000 की मानक कटौती लागू होती है।' , bn: 'A flat deduction of ₹75,000 is applied to your gross salary.', or: 'A flat deduction of ₹75,000 is applied to your gross salary.', ta: 'A flat deduction of ₹75,000 is applied to your gross salary.', te: 'A flat deduction of ₹75,000 is applied to your gross salary.' },
  'info.slabs_title':       { en: 'Tax slabs',              hi: 'कर स्लैब' , bn: 'কর স্ল্যাব', or: 'ক স্ল্যাব', ta: 'வரி அடுக்குகள்', te: 'పన్ను స్లాబ్‌లు' },
  'info.slabs_desc':        { en: 'The remaining income is taxed using the new regime slabs:', hi: 'शेष आय पर नई व्यवस्था के स्लैब के अनुसार कर लगता है:' , bn: 'The remaining income is taxed using the new regime slabs:', or: 'The remaining income is taxed using the new regime slabs:', ta: 'The remaining income is taxed using the new regime slabs:', te: 'The remaining income is taxed using the new regime slabs:' },
  'info.rebate_title':      { en: 'Section 87A rebate',     hi: 'धारा 87A छूट' , bn: 'ধারা 87A ছাড়', or: 'ধারা 87A ছাড়', ta: 'பிரிவு 87A தள்ளுபடி', te: 'సెక్షన్ 87A రాయితీ' },
  'info.rebate_desc':       { en: 'If your taxable income is ₹12,00,000 or less, your tax becomes zero (including cess).', hi: 'यदि आपकी कर योग्य आय ₹12,00,000 या कम है, तो आपका कर शून्य हो जाता है (सेस सहित)।' , bn: 'If your taxable income is ₹12,00,000 or less, your tax becomes zero (including cess).', or: 'If your taxable income is ₹12,00,000 or less, your tax becomes zero (including cess).', ta: 'If your taxable income is ₹12,00,000 or less, your tax becomes zero (including cess).', te: 'If your taxable income is ₹12,00,000 or less, your tax becomes zero (including cess).' },
  'info.cess_title':        { en: 'Health & education cess', hi: 'स्वास्थ्य एवं शिक्षा उपकर' , bn: 'স্বাস্থ্য ও শিক্ষা সেস', or: 'স্বাস্থ্য সেস', ta: 'சுகாதார & கல்வி சேஸ்', te: 'ఆరోగ్యం & విద్య సెస్' },
  'info.cess_desc':         { en: 'A 4% cess is applied on the final tax amount.', hi: 'अंतिम कर राशि पर 4% उपकर लगता है।' , bn: 'A 4% cess is applied on the final tax amount.', or: 'A 4% cess is applied on the final tax amount.', ta: 'A 4% cess is applied on the final tax amount.', te: 'A 4% cess is applied on the final tax amount.' },
  'info.equity_title':      { en: 'Equity stocks',          hi: 'इक्विटी शेयर' , bn: 'ইক্যুইটি শেয়ার', or: 'ই শেয়ার', ta: 'பங்குகள்', te: 'ఈక్విటీ స్టాక్స్' },
  'info.stcg_title':        { en: 'Short term capital gains (STCG)', hi: 'अल्पकालिक पूंजीगत लाभ (STCG)' , bn: 'স্বল্পমেয়াদী মূলধনী লাভ (STCG)', or: 'স STCG', ta: 'குறுகிய கால மூலதன ஆதாயம் (STCG)', te: 'స్వల్పకాలిక మూలధన లాభాలు (STCG)' },
  'info.stcg_desc':         { en: 'Shares sold within 1 year', hi: '1 वर्ष के अंदर बेचे गए शेयर' , bn: 'Shares sold within 1 year', or: 'Shares sold within 1 year', ta: 'Shares sold within 1 year', te: 'Shares sold within 1 year' },
  'info.stcg_15':           { en: '15% for sales before 23 July 2024', hi: '23 जुलाई 2024 से पहले की बिक्री पर 15%' , bn: '15% for sales before 23 July 2024', or: '15% for sales before 23 July 2024', ta: '15% for sales before 23 July 2024', te: '15% for sales before 23 July 2024' },
  'info.stcg_20':           { en: '20% for sales on or after 23 July 2024', hi: '23 जुलाई 2024 को या उसके बाद की बिक्री पर 20%' , bn: '20% for sales on or after 23 July 2024', or: '20% for sales on or after 23 July 2024', ta: '20% for sales on or after 23 July 2024', te: '20% for sales on or after 23 July 2024' },
  'info.ltcg_title':        { en: 'Long term capital gains (LTCG)', hi: 'दीर्घकालिक पूंजीगत लाभ (LTCG)' , bn: 'দীর্ঘমেয়াদী মূলধনী লাভ (LTCG)', or: 'দ LTCG', ta: 'நீண்ட கால மூலதன ஆதாயம் (LTCG)', te: 'దీర్ఘకాలిక మూలధన లాభాలు (LTCG)' },
  'info.ltcg_desc':         { en: 'Shares held for more than 1 year', hi: '1 वर्ष से अधिक रखे गए शेयर' , bn: 'Shares held for more than 1 year', or: 'Shares held for more than 1 year', ta: 'Shares held for more than 1 year', te: 'Shares held for more than 1 year' },
  'info.ltcg_exempt':       { en: 'First ₹1,25,000 is tax-free', hi: 'पहला ₹1,25,000 कर-मुक्त' , bn: 'First ₹1,25,000 is tax-free', or: 'First ₹1,25,000 is tax-free', ta: 'First ₹1,25,000 is tax-free', te: 'First ₹1,25,000 is tax-free' },
  'info.ltcg_above':        { en: 'Amount above exemption:',hi: 'छूट से ऊपर की राशि:' , bn: 'Amount above exemption:', or: 'Amount above exemption:', ta: 'Amount above exemption:', te: 'Amount above exemption:' },
  'info.ltcg_10':           { en: '10% before 23 July 2024',  hi: '23 जुलाई 2024 से पहले 10%' , bn: '10% before 23 July 2024', or: '10% before 23 July 2024', ta: '10% before 23 July 2024', te: '10% before 23 July 2024' },
  'info.ltcg_125':          { en: '12.5% after 23 July 2024', hi: '23 जुलाई 2024 के बाद 12.5%' , bn: '12.5% after 23 July 2024', or: '12.5% after 23 July 2024', ta: '12.5% after 23 July 2024', te: '12.5% after 23 July 2024' },
  'info.eq_mf_title':       { en: 'Equity mutual funds',    hi: 'इक्विटी म्यूचुअल फंड' , bn: 'ইক্যুইটি মিউচুয়াল ফান্ড', or: 'ই MF', ta: 'ஈக்விட்டி மியூச்சுவல் ஃபண்ட்', te: 'ఈక్విటీ మ్యూచువల్ ఫండ్స్' },
  'info.eq_mf_st_title':    { en: 'Short term (less than 1 year)', hi: 'अल्पकालिक (1 वर्ष से कम)' , bn: 'Short term (less than 1 year)', or: 'Short term (less than 1 year)', ta: 'Short term (less than 1 year)', te: 'Short term (less than 1 year)' },
  'info.eq_mf_st_desc':     { en: 'Taxed at 20%',           hi: '20% पर कर' , bn: 'Taxed at 20%', or: 'Taxed at 20%', ta: 'Taxed at 20%', te: 'Taxed at 20%' },
  'info.eq_mf_lt_title':    { en: 'Long term (more than 1 year)', hi: 'दीर्घकालिक (1 वर्ष से अधिक)' , bn: 'Long term (more than 1 year)', or: 'Long term (more than 1 year)', ta: 'Long term (more than 1 year)', te: 'Long term (more than 1 year)' },
  'info.eq_mf_lt_exempt':   { en: 'First ₹1,25,000 is exempt', hi: 'पहला ₹1,25,000 छूट में' , bn: 'First ₹1,25,000 is exempt', or: 'First ₹1,25,000 is exempt', ta: 'First ₹1,25,000 is exempt', te: 'First ₹1,25,000 is exempt' },
  'info.eq_mf_lt_rate':     { en: 'Remaining amount taxed at 12.5%', hi: 'शेष राशि पर 12.5% कर' , bn: 'Remaining amount taxed at 12.5%', or: 'Remaining amount taxed at 12.5%', ta: 'Remaining amount taxed at 12.5%', te: 'Remaining amount taxed at 12.5%' },
  'info.debt_mf_title':     { en: 'Debt mutual funds',      hi: 'डेट म्यूचुअल फंड' , bn: 'Debt mutual funds', or: 'Debt mutual funds', ta: 'Debt mutual funds', te: 'Debt mutual funds' },
  'info.debt_mf_desc':      { en: 'Post April 2023, all debt mutual fund gains are treated as normal income, regardless of holding period.', hi: 'अप्रैल 2023 के बाद, सभी डेट म्यूचुअल फंड लाभ को होल्डिंग अवधि की परवाह किए बिना सामान्य आय माना जाता है।' , bn: 'Post April 2023, all debt mutual fund gains are treated as normal income, regardless of holding period.', or: 'Post April 2023, all debt mutual fund gains are treated as normal income, regardless of holding period.', ta: 'Post April 2023, all debt mutual fund gains are treated as normal income, regardless of holding period.', te: 'Post April 2023, all debt mutual fund gains are treated as normal income, regardless of holding period.' },
  'info.debt_no_ltcg':      { en: '• No LTCG benefit',      hi: '• कोई LTCG लाभ नहीं' , bn: '• No LTCG benefit', or: '• No LTCG benefit', ta: '• No LTCG benefit', te: '• No LTCG benefit' },
  'info.debt_no_idx':       { en: '• No indexation',        hi: '• कोई इंडेक्सेशन नहीं' , bn: '• No indexation', or: '• No indexation', ta: '• No indexation', te: '• No indexation' },
  'info.debt_no_exempt':    { en: '• No exemption',         hi: '• कोई छूट नहीं' , bn: '• No exemption', or: '• No exemption', ta: '• No exemption', te: '• No exemption' },
  'info.debt_added':        { en: '• Added directly to salary income', hi: '• सीधे वेतन आय में जोड़ा जाता है' , bn: '• Added directly to salary income', or: '• Added directly to salary income', ta: '• Added directly to salary income', te: '• Added directly to salary income' },
  'info.debt_slab':         { en: '• Taxed as per your slab rate', hi: '• आपकी स्लैब दर के अनुसार कर' , bn: '• Taxed as per your slab rate', or: '• Taxed as per your slab rate', ta: '• Taxed as per your slab rate', te: '• Taxed as per your slab rate' },
  'info.debt_example':      { en: 'Example',                hi: 'उदाहरण' , bn: 'Example', or: 'Example', ta: 'Example', te: 'Example' },
  'info.debt_ex_salary':    { en: 'Salary',                 hi: 'वेतन' , bn: 'Salary', or: 'Salary', ta: 'Salary', te: 'Salary' },
  'info.debt_ex_gain':      { en: 'Debt MF gain',           hi: 'डेट MF लाभ' , bn: 'Debt MF gain', or: 'Debt MF gain', ta: 'Debt MF gain', te: 'Debt MF gain' },
  'info.debt_ex_total':     { en: 'Total income',           hi: 'कुल आय' , bn: 'Total income', or: 'Total income', ta: 'Total income', te: 'Total income' },
  'info.final_title':       { en: 'Final tax summary',      hi: 'अंतिम कर सारांश' , bn: 'Final tax summary', or: 'Final tax summary', ta: 'Final tax summary', te: 'Final tax summary' },
  'info.final_desc':        { en: 'Your final tax is the sum of:', hi: 'आपका अंतिम कर इनका योग है:' , bn: 'Your final tax is the sum of:', or: 'Your final tax is the sum of:', ta: 'Your final tax is the sum of:', te: 'Your final tax is the sum of:' },
  'info.final_1':           { en: '• Salary tax (including debt MF income)', hi: '• वेतन कर (डेट MF आय सहित)' , bn: '• Salary tax (including debt MF income)', or: '• Salary tax (including debt MF income)', ta: '• Salary tax (including debt MF income)', te: '• Salary tax (including debt MF income)' },
  'info.final_2':           { en: '• Equity stock capital gains tax', hi: '• इक्विटी शेयर पूंजीगत लाभ कर' , bn: '• Equity stock capital gains tax', or: '• Equity stock capital gains tax', ta: '• Equity stock capital gains tax', te: '• Equity stock capital gains tax' },
  'info.final_3':           { en: '• Equity mutual fund tax', hi: '• इक्विटी म्यूचुअल फंड कर' , bn: '• Equity mutual fund tax', or: '• Equity mutual fund tax', ta: '• Equity mutual fund tax', te: '• Equity mutual fund tax' },
  'info.tds_sub':           { en: 'From this total, any TDS already deducted is subtracted.', hi: 'इस कुल से, पहले से काटा गया TDS घटाया जाता है।' , bn: 'From this total, any TDS already deducted is subtracted.', or: 'From this total, any TDS already deducted is subtracted.', ta: 'From this total, any TDS already deducted is subtracted.', te: 'From this total, any TDS already deducted is subtracted.' },
  'info.if_tds_gt':         { en: 'If TDS > total tax',    hi: 'यदि TDS > कुल कर' , bn: 'If TDS > total tax', or: 'If TDS > total tax', ta: 'If TDS > total tax', te: 'If TDS > total tax' },
  'info.refund_due':        { en: 'Refund due',             hi: 'वापसी देय' , bn: 'Refund due', or: 'Refund due', ta: 'Refund due', te: 'Refund due' },
  'info.if_tds_lt':         { en: 'If TDS < total tax',    hi: 'यदि TDS < कुल कर' , bn: 'If TDS < total tax', or: 'If TDS < total tax', ta: 'If TDS < total tax', te: 'If TDS < total tax' },
  'info.tax_payable':       { en: 'Tax payable',            hi: 'देय कर' , bn: 'Tax payable', or: 'Tax payable', ta: 'Tax payable', te: 'Tax payable' },
  'info.disclaimer':        { en: 'SmartTax follows the latest available income tax rules. This explanation is for clarity and education. Final liability may vary based on personal circumstances.', hi: 'SmartTax नवीनतम आयकर नियमों का पालन करता है। यह स्पष्टता और शिक्षा के लिए है। अंतिम देयता व्यक्तिगत परिस्थितियों के आधार पर भिन्न हो सकती है।' , bn: 'SmartTax follows the latest available income tax rules. This explanation is for clarity and education. Final liability may vary based on personal circumstances.', or: 'SmartTax follows the latest available income tax rules. This explanation is for clarity and education. Final liability may vary based on personal circumstances.', ta: 'SmartTax follows the latest available income tax rules. This explanation is for clarity and education. Final liability may vary based on personal circumstances.', te: 'SmartTax follows the latest available income tax rules. This explanation is for clarity and education. Final liability may vary based on personal circumstances.' },
  'info.nil':               { en: 'Nil',  hi: 'शून्य' , bn: 'Nil', or: 'Nil', ta: 'Nil', te: 'Nil' },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() =>
    (localStorage.getItem('smarttax_lang') as Language) ?? 'en'
  );

  useEffect(() => {
    localStorage.setItem('smarttax_lang', lang);
  }, [lang]);

  const LANG_CYCLE: Language[] = ['en', 'hi', 'bn', 'or', 'ta', 'te'];
  const toggleLang = () => setLang(prev => { const i = LANG_CYCLE.indexOf(prev); return LANG_CYCLE[(i + 1) % LANG_CYCLE.length]; });

  const t = (key: string): string => T[key]?.[lang] ?? T[key]?.['en'] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = (): LanguageContextValue => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider');
  return ctx;
};
